/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
  type AdditionalDataHolder,
  type BaseRequestBuilder,
  type Parsable,
  type ParsableFactory,
  type ParseNode,
  type RequestConfiguration,
  type RequestInformation,
  type RequestsMetadata,
  type SerializationWriter,
} from "@microsoft/kiota-abstractions";

/**
 * 作者一覧
 */
export interface AuthorSearchGetResponse
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The request property
   */
  request?: AuthorSearchGetResponse_request;
  /**
   * The result property
   */
  result?: AuthorSearchGetResponse_result;
}
export interface AuthorSearchGetResponse_request
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The parameters property
   */
  parameters?: AuthorSearchGetResponse_request_parameters;
}
export interface AuthorSearchGetResponse_request_parameters
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The affiliate_id property
   */
  affiliate_id?: string;
  /**
   * The api_id property
   */
  api_id?: string;
  /**
   * The floor_id property
   */
  floor_id?: string;
  /**
   * The hits property
   */
  hits?: string;
  /**
   * The initial property
   */
  initial?: string;
  /**
   * The output property
   */
  output?: string;
}
export interface AuthorSearchGetResponse_result
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The author property
   */
  author?: AuthorSearchGetResponse_result_author[];
  /**
   * The first_position property
   */
  first_position?: number;
  /**
   * The floor_code property
   */
  floor_code?: string;
  /**
   * The floor_id property
   */
  floor_id?: string;
  /**
   * The floor_name property
   */
  floor_name?: string;
  /**
   * The result_count property
   */
  result_count?: number;
  /**
   * The service_code property
   */
  service_code?: string;
  /**
   * The service_name property
   */
  service_name?: string;
  /**
   * The site_code property
   */
  site_code?: string;
  /**
   * The site_name property
   */
  site_name?: string;
  /**
   * The status property
   */
  status?: string;
  /**
   * The total_count property
   */
  total_count?: string;
}
export interface AuthorSearchGetResponse_result_author
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The author_id property
   */
  author_id?: string;
  /**
   * The list_url property
   */
  list_url?: string;
  /**
   * The name property
   */
  name?: string;
  /**
   * The ruby property
   */
  ruby?: string;
}
/**
 * Builds and executes requests for operations under /AuthorSearch
 */
export interface AuthorSearchRequestBuilder
  extends BaseRequestBuilder<AuthorSearchRequestBuilder> {
  /**
   * 作者一覧を取得することが可能がAPIです。```curlhttps://api.dmm.com/affiliate/v3/AuthorSearch?api_id=[APIID]&affiliate_id=[アフィリエイトID]&iniital=%e3%81%86&floor_id=27&hits=10&output=json```
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {Promise<AuthorSearchGetResponse>}
   */
  get(
    requestConfiguration?:
      | RequestConfiguration<AuthorSearchRequestBuilderGetQueryParameters>
      | undefined,
  ): Promise<AuthorSearchGetResponse | undefined>;
  /**
   * 作者一覧を取得することが可能がAPIです。```curlhttps://api.dmm.com/affiliate/v3/AuthorSearch?api_id=[APIID]&affiliate_id=[アフィリエイトID]&iniital=%e3%81%86&floor_id=27&hits=10&output=json```
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {RequestInformation}
   */
  toGetRequestInformation(
    requestConfiguration?:
      | RequestConfiguration<AuthorSearchRequestBuilderGetQueryParameters>
      | undefined,
  ): RequestInformation;
}
/**
 * 作者一覧を取得することが可能がAPIです。```curlhttps://api.dmm.com/affiliate/v3/AuthorSearch?api_id=[APIID]&affiliate_id=[アフィリエイトID]&iniital=%e3%81%86&floor_id=27&hits=10&output=json```
 */
export interface AuthorSearchRequestBuilderGetQueryParameters {
  /**
   * 出力形式jsonで指定した場合に、このパラメータでコールバック関数名を指定すると、JSONP形式で出力されます
   */
  callback?: string;
  /**
   * フロア検索APIから取得可能なフロアID
   */
  floorId?: string;
  /**
   * 取得件数初期値：100　最大：500
   */
  hits?: number;
  /**
   * 頭文字(50音) 50音をUTF-8で指定
   */
  initial?: string;
  /**
   * 検索開始位置初期値：1
   */
  offset?: number;
  /**
   * 出力形式
   */
  output?: GetOutputQueryParameterType;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AuthorSearchGetResponse_request_parameters}
 */
// @ts-ignore
export function createAuthorSearchGetResponse_request_parametersFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoAuthorSearchGetResponse_request_parameters;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AuthorSearchGetResponse_request}
 */
// @ts-ignore
export function createAuthorSearchGetResponse_requestFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoAuthorSearchGetResponse_request;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AuthorSearchGetResponse_result_author}
 */
// @ts-ignore
export function createAuthorSearchGetResponse_result_authorFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoAuthorSearchGetResponse_result_author;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AuthorSearchGetResponse_result}
 */
// @ts-ignore
export function createAuthorSearchGetResponse_resultFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoAuthorSearchGetResponse_result;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AuthorSearchGetResponse}
 */
// @ts-ignore
export function createAuthorSearchGetResponseFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoAuthorSearchGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAuthorSearchGetResponse(
  authorSearchGetResponse: Partial<AuthorSearchGetResponse> | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "request": (n) => {
      authorSearchGetResponse.request = n.getObjectValue<
        AuthorSearchGetResponse_request
      >(createAuthorSearchGetResponse_requestFromDiscriminatorValue);
    },
    "result": (n) => {
      authorSearchGetResponse.result = n.getObjectValue<
        AuthorSearchGetResponse_result
      >(createAuthorSearchGetResponse_resultFromDiscriminatorValue);
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAuthorSearchGetResponse_request(
  authorSearchGetResponse_request:
    | Partial<AuthorSearchGetResponse_request>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "parameters": (n) => {
      authorSearchGetResponse_request.parameters = n.getObjectValue<
        AuthorSearchGetResponse_request_parameters
      >(createAuthorSearchGetResponse_request_parametersFromDiscriminatorValue);
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAuthorSearchGetResponse_request_parameters(
  authorSearchGetResponse_request_parameters:
    | Partial<AuthorSearchGetResponse_request_parameters>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "affiliate_id": (n) => {
      authorSearchGetResponse_request_parameters.affiliate_id = n
        .getStringValue();
    },
    "api_id": (n) => {
      authorSearchGetResponse_request_parameters.api_id = n.getStringValue();
    },
    "floor_id": (n) => {
      authorSearchGetResponse_request_parameters.floor_id = n.getStringValue();
    },
    "hits": (n) => {
      authorSearchGetResponse_request_parameters.hits = n.getStringValue();
    },
    "initial": (n) => {
      authorSearchGetResponse_request_parameters.initial = n.getStringValue();
    },
    "output": (n) => {
      authorSearchGetResponse_request_parameters.output = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAuthorSearchGetResponse_result(
  authorSearchGetResponse_result:
    | Partial<AuthorSearchGetResponse_result>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "author": (n) => {
      authorSearchGetResponse_result.author = n.getCollectionOfObjectValues<
        AuthorSearchGetResponse_result_author
      >(createAuthorSearchGetResponse_result_authorFromDiscriminatorValue);
    },
    "first_position": (n) => {
      authorSearchGetResponse_result.first_position = n.getNumberValue();
    },
    "floor_code": (n) => {
      authorSearchGetResponse_result.floor_code = n.getStringValue();
    },
    "floor_id": (n) => {
      authorSearchGetResponse_result.floor_id = n.getStringValue();
    },
    "floor_name": (n) => {
      authorSearchGetResponse_result.floor_name = n.getStringValue();
    },
    "result_count": (n) => {
      authorSearchGetResponse_result.result_count = n.getNumberValue();
    },
    "service_code": (n) => {
      authorSearchGetResponse_result.service_code = n.getStringValue();
    },
    "service_name": (n) => {
      authorSearchGetResponse_result.service_name = n.getStringValue();
    },
    "site_code": (n) => {
      authorSearchGetResponse_result.site_code = n.getStringValue();
    },
    "site_name": (n) => {
      authorSearchGetResponse_result.site_name = n.getStringValue();
    },
    "status": (n) => {
      authorSearchGetResponse_result.status = n.getStringValue();
    },
    "total_count": (n) => {
      authorSearchGetResponse_result.total_count = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAuthorSearchGetResponse_result_author(
  authorSearchGetResponse_result_author:
    | Partial<AuthorSearchGetResponse_result_author>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "author_id": (n) => {
      authorSearchGetResponse_result_author.author_id = n.getStringValue();
    },
    "list_url": (n) => {
      authorSearchGetResponse_result_author.list_url = n.getStringValue();
    },
    "name": (n) => {
      authorSearchGetResponse_result_author.name = n.getStringValue();
    },
    "ruby": (n) => {
      authorSearchGetResponse_result_author.ruby = n.getStringValue();
    },
  };
}
export type GetOutputQueryParameterType =
  (typeof GetOutputQueryParameterTypeObject)[
    keyof typeof GetOutputQueryParameterTypeObject
  ];
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAuthorSearchGetResponse(
  writer: SerializationWriter,
  authorSearchGetResponse: Partial<AuthorSearchGetResponse> | undefined = {},
): void {
  writer.writeObjectValue<AuthorSearchGetResponse_request>(
    "request",
    authorSearchGetResponse.request,
    serializeAuthorSearchGetResponse_request,
  );
  writer.writeObjectValue<AuthorSearchGetResponse_result>(
    "result",
    authorSearchGetResponse.result,
    serializeAuthorSearchGetResponse_result,
  );
  writer.writeAdditionalData(authorSearchGetResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAuthorSearchGetResponse_request(
  writer: SerializationWriter,
  authorSearchGetResponse_request:
    | Partial<AuthorSearchGetResponse_request>
    | undefined = {},
): void {
  writer.writeObjectValue<AuthorSearchGetResponse_request_parameters>(
    "parameters",
    authorSearchGetResponse_request.parameters,
    serializeAuthorSearchGetResponse_request_parameters,
  );
  writer.writeAdditionalData(authorSearchGetResponse_request.additionalData);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAuthorSearchGetResponse_request_parameters(
  writer: SerializationWriter,
  authorSearchGetResponse_request_parameters:
    | Partial<AuthorSearchGetResponse_request_parameters>
    | undefined = {},
): void {
  writer.writeStringValue(
    "affiliate_id",
    authorSearchGetResponse_request_parameters.affiliate_id,
  );
  writer.writeStringValue(
    "api_id",
    authorSearchGetResponse_request_parameters.api_id,
  );
  writer.writeStringValue(
    "floor_id",
    authorSearchGetResponse_request_parameters.floor_id,
  );
  writer.writeStringValue(
    "hits",
    authorSearchGetResponse_request_parameters.hits,
  );
  writer.writeStringValue(
    "initial",
    authorSearchGetResponse_request_parameters.initial,
  );
  writer.writeStringValue(
    "output",
    authorSearchGetResponse_request_parameters.output,
  );
  writer.writeAdditionalData(
    authorSearchGetResponse_request_parameters.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAuthorSearchGetResponse_result(
  writer: SerializationWriter,
  authorSearchGetResponse_result:
    | Partial<AuthorSearchGetResponse_result>
    | undefined = {},
): void {
  writer.writeCollectionOfObjectValues<AuthorSearchGetResponse_result_author>(
    "author",
    authorSearchGetResponse_result.author,
    serializeAuthorSearchGetResponse_result_author,
  );
  writer.writeNumberValue(
    "first_position",
    authorSearchGetResponse_result.first_position,
  );
  writer.writeStringValue(
    "floor_code",
    authorSearchGetResponse_result.floor_code,
  );
  writer.writeStringValue("floor_id", authorSearchGetResponse_result.floor_id);
  writer.writeStringValue(
    "floor_name",
    authorSearchGetResponse_result.floor_name,
  );
  writer.writeNumberValue(
    "result_count",
    authorSearchGetResponse_result.result_count,
  );
  writer.writeStringValue(
    "service_code",
    authorSearchGetResponse_result.service_code,
  );
  writer.writeStringValue(
    "service_name",
    authorSearchGetResponse_result.service_name,
  );
  writer.writeStringValue(
    "site_code",
    authorSearchGetResponse_result.site_code,
  );
  writer.writeStringValue(
    "site_name",
    authorSearchGetResponse_result.site_name,
  );
  writer.writeStringValue("status", authorSearchGetResponse_result.status);
  writer.writeStringValue(
    "total_count",
    authorSearchGetResponse_result.total_count,
  );
  writer.writeAdditionalData(authorSearchGetResponse_result.additionalData);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAuthorSearchGetResponse_result_author(
  writer: SerializationWriter,
  authorSearchGetResponse_result_author:
    | Partial<AuthorSearchGetResponse_result_author>
    | undefined = {},
): void {
  writer.writeStringValue(
    "author_id",
    authorSearchGetResponse_result_author.author_id,
  );
  writer.writeStringValue(
    "list_url",
    authorSearchGetResponse_result_author.list_url,
  );
  writer.writeStringValue("name", authorSearchGetResponse_result_author.name);
  writer.writeStringValue("ruby", authorSearchGetResponse_result_author.ruby);
  writer.writeAdditionalData(
    authorSearchGetResponse_result_author.additionalData,
  );
}
/**
 * Uri template for the request builder.
 */
export const AuthorSearchRequestBuilderUriTemplate =
  "{+baseurl}/AuthorSearch?floor_id={floor_id}{&callback*,hits*,initial*,offset*,output*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const AuthorSearchRequestBuilderGetQueryParametersMapper: Record<
  string,
  string
> = {
  "floorId": "floor_id",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const AuthorSearchRequestBuilderRequestsMetadata: RequestsMetadata = {
  get: {
    uriTemplate: AuthorSearchRequestBuilderUriTemplate,
    responseBodyContentType: "application/json",
    adapterMethodName: "send",
    responseBodyFactory: createAuthorSearchGetResponseFromDiscriminatorValue,
    queryParametersMapper: AuthorSearchRequestBuilderGetQueryParametersMapper,
  },
};
export const GetOutputQueryParameterTypeObject = {
  Json: "json",
  Xml: "xml",
} as const;
/* tslint:enable */
/* eslint-enable */
