/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
  type AdditionalDataHolder,
  type BaseRequestBuilder,
  type Parsable,
  type ParsableFactory,
  type ParseNode,
  type RequestConfiguration,
  type RequestInformation,
  type RequestsMetadata,
  type SerializationWriter,
} from "@microsoft/kiota-abstractions";

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_request_parameters}
 */
// @ts-ignore
export function createItemListGetResponse_request_parametersFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_request_parameters;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_request}
 */
// @ts-ignore
export function createItemListGetResponse_requestFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_request;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_campaign}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_campaignFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_campaign;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_cdinfo}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_cdinfoFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_cdinfo;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_directory}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_directoryFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_directory;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_imageURL}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_imageURLFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_imageURL;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_iteminfo_actor}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_iteminfo_actorFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_iteminfo_actor;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_iteminfo_actress}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_iteminfo_actressFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_iteminfo_actress;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_iteminfo_author}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_iteminfo_authorFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_iteminfo_author;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_iteminfo_color}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_iteminfo_colorFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_iteminfo_color;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_iteminfo_director}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_iteminfo_directorFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_iteminfo_director;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_iteminfo_genre}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_iteminfo_genreFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_iteminfo_genre;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_iteminfo_label}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_iteminfo_labelFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_iteminfo_label;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_iteminfo_maker}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_iteminfo_makerFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_iteminfo_maker;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_iteminfo_manufacture}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_iteminfo_manufactureFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_iteminfo_manufacture;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_iteminfo_series}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_iteminfo_seriesFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_iteminfo_series;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_iteminfo_size}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_iteminfo_sizeFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_iteminfo_size;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_iteminfo_type}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_iteminfo_typeFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_iteminfo_type;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_iteminfo}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_iteminfoFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_iteminfo;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_prices_deliveries_delivery}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_prices_deliveries_deliveryFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_prices_deliveries_delivery;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_prices_deliveries}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_prices_deliveriesFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_prices_deliveries;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_prices}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_pricesFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_prices;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_review}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_reviewFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_review;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_sampleImageURL_sample_l}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_sampleImageURL_sample_lFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_sampleImageURL_sample_l;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_sampleImageURL_sample_s}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_sampleImageURL_sample_sFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_sampleImageURL_sample_s;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_sampleImageURL}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_sampleImageURLFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_sampleImageURL;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_sampleMovieURL}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_sampleMovieURLFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_sampleMovieURL;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items_tachiyomi}
 */
// @ts-ignore
export function createItemListGetResponse_result_items_tachiyomiFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items_tachiyomi;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result_items}
 */
// @ts-ignore
export function createItemListGetResponse_result_itemsFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result_items;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse_result}
 */
// @ts-ignore
export function createItemListGetResponse_resultFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse_result;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ItemListGetResponse}
 */
// @ts-ignore
export function createItemListGetResponseFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoItemListGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse(
  itemListGetResponse: Partial<ItemListGetResponse> | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "request": (n) => {
      itemListGetResponse.request = n.getObjectValue<
        ItemListGetResponse_request
      >(createItemListGetResponse_requestFromDiscriminatorValue);
    },
    "result": (n) => {
      itemListGetResponse.result = n.getObjectValue<ItemListGetResponse_result>(
        createItemListGetResponse_resultFromDiscriminatorValue,
      );
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_request(
  itemListGetResponse_request:
    | Partial<ItemListGetResponse_request>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "parameters": (n) => {
      itemListGetResponse_request.parameters = n.getObjectValue<
        ItemListGetResponse_request_parameters
      >(createItemListGetResponse_request_parametersFromDiscriminatorValue);
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_request_parameters(
  itemListGetResponse_request_parameters:
    | Partial<ItemListGetResponse_request_parameters>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "affiliate_id": (n) => {
      itemListGetResponse_request_parameters.affiliate_id = n.getStringValue();
    },
    "api_id": (n) => {
      itemListGetResponse_request_parameters.api_id = n.getStringValue();
    },
    "floor": (n) => {
      itemListGetResponse_request_parameters.floor = n.getStringValue();
    },
    "keyword": (n) => {
      itemListGetResponse_request_parameters.keyword = n.getStringValue();
    },
    "service": (n) => {
      itemListGetResponse_request_parameters.service = n.getStringValue();
    },
    "site": (n) => {
      itemListGetResponse_request_parameters.site = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result(
  itemListGetResponse_result: Partial<ItemListGetResponse_result> | undefined =
    {},
): Record<string, (node: ParseNode) => void> {
  return {
    "first_position": (n) => {
      itemListGetResponse_result.first_position = n.getNumberValue();
    },
    "items": (n) => {
      itemListGetResponse_result.items = n.getCollectionOfObjectValues<
        ItemListGetResponse_result_items
      >(createItemListGetResponse_result_itemsFromDiscriminatorValue);
    },
    "result_count": (n) => {
      itemListGetResponse_result.result_count = n.getNumberValue();
    },
    "status": (n) => {
      itemListGetResponse_result.status = n.getNumberValue();
    },
    "total_count": (n) => {
      itemListGetResponse_result.total_count = n.getNumberValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items(
  itemListGetResponse_result_items:
    | Partial<ItemListGetResponse_result_items>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "affiliateURL": (n) => {
      itemListGetResponse_result_items.affiliateURL = n.getStringValue();
    },
    "campaign": (n) => {
      itemListGetResponse_result_items.campaign = n.getObjectValue<
        ItemListGetResponse_result_items_campaign
      >(createItemListGetResponse_result_items_campaignFromDiscriminatorValue);
    },
    "category_name": (n) => {
      itemListGetResponse_result_items.category_name = n.getStringValue();
    },
    "cdinfo": (n) => {
      itemListGetResponse_result_items.cdinfo = n.getObjectValue<
        ItemListGetResponse_result_items_cdinfo
      >(createItemListGetResponse_result_items_cdinfoFromDiscriminatorValue);
    },
    "content_id": (n) => {
      itemListGetResponse_result_items.content_id = n.getStringValue();
    },
    "date": (n) => {
      itemListGetResponse_result_items.date = n.getStringValue();
    },
    "directory": (n) => {
      itemListGetResponse_result_items.directory = n.getObjectValue<
        ItemListGetResponse_result_items_directory
      >(createItemListGetResponse_result_items_directoryFromDiscriminatorValue);
    },
    "floor_code": (n) => {
      itemListGetResponse_result_items.floor_code = n.getStringValue();
    },
    "floor_name": (n) => {
      itemListGetResponse_result_items.floor_name = n.getStringValue();
    },
    "imageURL": (n) => {
      itemListGetResponse_result_items.imageURL = n.getObjectValue<
        ItemListGetResponse_result_items_imageURL
      >(createItemListGetResponse_result_items_imageURLFromDiscriminatorValue);
    },
    "isbn": (n) => {
      itemListGetResponse_result_items.isbn = n.getStringValue();
    },
    "iteminfo": (n) => {
      itemListGetResponse_result_items.iteminfo = n.getObjectValue<
        ItemListGetResponse_result_items_iteminfo
      >(createItemListGetResponse_result_items_iteminfoFromDiscriminatorValue);
    },
    "jancode": (n) => {
      itemListGetResponse_result_items.jancode = n.getStringValue();
    },
    "maker_product": (n) => {
      itemListGetResponse_result_items.maker_product = n.getStringValue();
    },
    "number": (n) => {
      itemListGetResponse_result_items.number = n.getStringValue();
    },
    "prices": (n) => {
      itemListGetResponse_result_items.prices = n.getObjectValue<
        ItemListGetResponse_result_items_prices
      >(createItemListGetResponse_result_items_pricesFromDiscriminatorValue);
    },
    "product_id": (n) => {
      itemListGetResponse_result_items.product_id = n.getStringValue();
    },
    "review": (n) => {
      itemListGetResponse_result_items.review = n.getObjectValue<
        ItemListGetResponse_result_items_review
      >(createItemListGetResponse_result_items_reviewFromDiscriminatorValue);
    },
    "sampleImageURL": (n) => {
      itemListGetResponse_result_items.sampleImageURL = n.getObjectValue<
        ItemListGetResponse_result_items_sampleImageURL
      >(createItemListGetResponse_result_items_sampleImageURLFromDiscriminatorValue);
    },
    "sampleMovieURL": (n) => {
      itemListGetResponse_result_items.sampleMovieURL = n.getObjectValue<
        ItemListGetResponse_result_items_sampleMovieURL
      >(createItemListGetResponse_result_items_sampleMovieURLFromDiscriminatorValue);
    },
    "service_code": (n) => {
      itemListGetResponse_result_items.service_code = n.getStringValue();
    },
    "service_name": (n) => {
      itemListGetResponse_result_items.service_name = n.getStringValue();
    },
    "stock": (n) => {
      itemListGetResponse_result_items.stock = n.getStringValue();
    },
    "tachiyomi": (n) => {
      itemListGetResponse_result_items.tachiyomi = n.getObjectValue<
        ItemListGetResponse_result_items_tachiyomi
      >(createItemListGetResponse_result_items_tachiyomiFromDiscriminatorValue);
    },
    "title": (n) => {
      itemListGetResponse_result_items.title = n.getStringValue();
    },
    "URL": (n) => {
      itemListGetResponse_result_items.uRL = n.getStringValue();
    },
    "volume": (n) => {
      itemListGetResponse_result_items.volume = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_campaign(
  itemListGetResponse_result_items_campaign:
    | Partial<ItemListGetResponse_result_items_campaign>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "date_begin": (n) => {
      itemListGetResponse_result_items_campaign.date_begin = n.getStringValue();
    },
    "date_end": (n) => {
      itemListGetResponse_result_items_campaign.date_end = n.getStringValue();
    },
    "title": (n) => {
      itemListGetResponse_result_items_campaign.title = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_cdinfo(
  itemListGetResponse_result_items_cdinfo:
    | Partial<ItemListGetResponse_result_items_cdinfo>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "kind": (n) => {
      itemListGetResponse_result_items_cdinfo.kind = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_directory(
  itemListGetResponse_result_items_directory:
    | Partial<ItemListGetResponse_result_items_directory>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "id": (n) => {
      itemListGetResponse_result_items_directory.id = n.getStringValue();
    },
    "name": (n) => {
      itemListGetResponse_result_items_directory.name = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_imageURL(
  itemListGetResponse_result_items_imageURL:
    | Partial<ItemListGetResponse_result_items_imageURL>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "large": (n) => {
      itemListGetResponse_result_items_imageURL.large = n.getStringValue();
    },
    "list": (n) => {
      itemListGetResponse_result_items_imageURL.list = n.getStringValue();
    },
    "small": (n) => {
      itemListGetResponse_result_items_imageURL.small = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_iteminfo(
  itemListGetResponse_result_items_iteminfo:
    | Partial<ItemListGetResponse_result_items_iteminfo>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "actor": (n) => {
      itemListGetResponse_result_items_iteminfo.actor = n
        .getCollectionOfObjectValues<
          ItemListGetResponse_result_items_iteminfo_actor
        >(createItemListGetResponse_result_items_iteminfo_actorFromDiscriminatorValue);
    },
    "actress": (n) => {
      itemListGetResponse_result_items_iteminfo.actress = n
        .getCollectionOfObjectValues<
          ItemListGetResponse_result_items_iteminfo_actress
        >(createItemListGetResponse_result_items_iteminfo_actressFromDiscriminatorValue);
    },
    "author": (n) => {
      itemListGetResponse_result_items_iteminfo.author = n
        .getCollectionOfObjectValues<
          ItemListGetResponse_result_items_iteminfo_author
        >(createItemListGetResponse_result_items_iteminfo_authorFromDiscriminatorValue);
    },
    "color": (n) => {
      itemListGetResponse_result_items_iteminfo.color = n
        .getCollectionOfObjectValues<
          ItemListGetResponse_result_items_iteminfo_color
        >(createItemListGetResponse_result_items_iteminfo_colorFromDiscriminatorValue);
    },
    "director": (n) => {
      itemListGetResponse_result_items_iteminfo.director = n
        .getCollectionOfObjectValues<
          ItemListGetResponse_result_items_iteminfo_director
        >(createItemListGetResponse_result_items_iteminfo_directorFromDiscriminatorValue);
    },
    "genre": (n) => {
      itemListGetResponse_result_items_iteminfo.genre = n
        .getCollectionOfObjectValues<
          ItemListGetResponse_result_items_iteminfo_genre
        >(createItemListGetResponse_result_items_iteminfo_genreFromDiscriminatorValue);
    },
    "label": (n) => {
      itemListGetResponse_result_items_iteminfo.label = n
        .getCollectionOfObjectValues<
          ItemListGetResponse_result_items_iteminfo_label
        >(createItemListGetResponse_result_items_iteminfo_labelFromDiscriminatorValue);
    },
    "maker": (n) => {
      itemListGetResponse_result_items_iteminfo.maker = n
        .getCollectionOfObjectValues<
          ItemListGetResponse_result_items_iteminfo_maker
        >(createItemListGetResponse_result_items_iteminfo_makerFromDiscriminatorValue);
    },
    "manufacture": (n) => {
      itemListGetResponse_result_items_iteminfo.manufacture = n
        .getCollectionOfObjectValues<
          ItemListGetResponse_result_items_iteminfo_manufacture
        >(createItemListGetResponse_result_items_iteminfo_manufactureFromDiscriminatorValue);
    },
    "series": (n) => {
      itemListGetResponse_result_items_iteminfo.series = n
        .getCollectionOfObjectValues<
          ItemListGetResponse_result_items_iteminfo_series
        >(createItemListGetResponse_result_items_iteminfo_seriesFromDiscriminatorValue);
    },
    "size": (n) => {
      itemListGetResponse_result_items_iteminfo.size = n
        .getCollectionOfObjectValues<
          ItemListGetResponse_result_items_iteminfo_size
        >(createItemListGetResponse_result_items_iteminfo_sizeFromDiscriminatorValue);
    },
    "type": (n) => {
      itemListGetResponse_result_items_iteminfo.type = n
        .getCollectionOfObjectValues<
          ItemListGetResponse_result_items_iteminfo_type
        >(createItemListGetResponse_result_items_iteminfo_typeFromDiscriminatorValue);
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_iteminfo_actor(
  itemListGetResponse_result_items_iteminfo_actor:
    | Partial<ItemListGetResponse_result_items_iteminfo_actor>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "id": (n) => {
      itemListGetResponse_result_items_iteminfo_actor.id = n.getNumberValue();
    },
    "name": (n) => {
      itemListGetResponse_result_items_iteminfo_actor.name = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_iteminfo_actress(
  itemListGetResponse_result_items_iteminfo_actress:
    | Partial<ItemListGetResponse_result_items_iteminfo_actress>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "id": (n) => {
      itemListGetResponse_result_items_iteminfo_actress.id = n.getNumberValue();
    },
    "name": (n) => {
      itemListGetResponse_result_items_iteminfo_actress.name = n
        .getStringValue();
    },
    "ruby": (n) => {
      itemListGetResponse_result_items_iteminfo_actress.ruby = n
        .getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_iteminfo_author(
  itemListGetResponse_result_items_iteminfo_author:
    | Partial<ItemListGetResponse_result_items_iteminfo_author>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "id": (n) => {
      itemListGetResponse_result_items_iteminfo_author.id = n.getNumberValue();
    },
    "name": (n) => {
      itemListGetResponse_result_items_iteminfo_author.name = n
        .getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_iteminfo_color(
  itemListGetResponse_result_items_iteminfo_color:
    | Partial<ItemListGetResponse_result_items_iteminfo_color>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "id": (n) => {
      itemListGetResponse_result_items_iteminfo_color.id = n.getNumberValue();
    },
    "name": (n) => {
      itemListGetResponse_result_items_iteminfo_color.name = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_iteminfo_director(
  itemListGetResponse_result_items_iteminfo_director:
    | Partial<ItemListGetResponse_result_items_iteminfo_director>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "id": (n) => {
      itemListGetResponse_result_items_iteminfo_director.id = n
        .getNumberValue();
    },
    "name": (n) => {
      itemListGetResponse_result_items_iteminfo_director.name = n
        .getStringValue();
    },
    "ruby": (n) => {
      itemListGetResponse_result_items_iteminfo_director.ruby = n
        .getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_iteminfo_genre(
  itemListGetResponse_result_items_iteminfo_genre:
    | Partial<ItemListGetResponse_result_items_iteminfo_genre>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "id": (n) => {
      itemListGetResponse_result_items_iteminfo_genre.id = n.getNumberValue();
    },
    "name": (n) => {
      itemListGetResponse_result_items_iteminfo_genre.name = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_iteminfo_label(
  itemListGetResponse_result_items_iteminfo_label:
    | Partial<ItemListGetResponse_result_items_iteminfo_label>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "id": (n) => {
      itemListGetResponse_result_items_iteminfo_label.id = n.getNumberValue();
    },
    "name": (n) => {
      itemListGetResponse_result_items_iteminfo_label.name = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_iteminfo_maker(
  itemListGetResponse_result_items_iteminfo_maker:
    | Partial<ItemListGetResponse_result_items_iteminfo_maker>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "id": (n) => {
      itemListGetResponse_result_items_iteminfo_maker.id = n.getNumberValue();
    },
    "name": (n) => {
      itemListGetResponse_result_items_iteminfo_maker.name = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_iteminfo_manufacture(
  itemListGetResponse_result_items_iteminfo_manufacture:
    | Partial<ItemListGetResponse_result_items_iteminfo_manufacture>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "id": (n) => {
      itemListGetResponse_result_items_iteminfo_manufacture.id = n
        .getNumberValue();
    },
    "name": (n) => {
      itemListGetResponse_result_items_iteminfo_manufacture.name = n
        .getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_iteminfo_series(
  itemListGetResponse_result_items_iteminfo_series:
    | Partial<ItemListGetResponse_result_items_iteminfo_series>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "id": (n) => {
      itemListGetResponse_result_items_iteminfo_series.id = n.getNumberValue();
    },
    "name": (n) => {
      itemListGetResponse_result_items_iteminfo_series.name = n
        .getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_iteminfo_size(
  itemListGetResponse_result_items_iteminfo_size:
    | Partial<ItemListGetResponse_result_items_iteminfo_size>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "id": (n) => {
      itemListGetResponse_result_items_iteminfo_size.id = n.getNumberValue();
    },
    "name": (n) => {
      itemListGetResponse_result_items_iteminfo_size.name = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_iteminfo_type(
  itemListGetResponse_result_items_iteminfo_type:
    | Partial<ItemListGetResponse_result_items_iteminfo_type>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "id": (n) => {
      itemListGetResponse_result_items_iteminfo_type.id = n.getNumberValue();
    },
    "name": (n) => {
      itemListGetResponse_result_items_iteminfo_type.name = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_prices(
  itemListGetResponse_result_items_prices:
    | Partial<ItemListGetResponse_result_items_prices>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "deliveries": (n) => {
      itemListGetResponse_result_items_prices.deliveries = n.getObjectValue<
        ItemListGetResponse_result_items_prices_deliveries
      >(createItemListGetResponse_result_items_prices_deliveriesFromDiscriminatorValue);
    },
    "list_price": (n) => {
      itemListGetResponse_result_items_prices.list_price = n.getStringValue();
    },
    "price": (n) => {
      itemListGetResponse_result_items_prices.price = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_prices_deliveries(
  itemListGetResponse_result_items_prices_deliveries:
    | Partial<ItemListGetResponse_result_items_prices_deliveries>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "delivery": (n) => {
      itemListGetResponse_result_items_prices_deliveries.delivery = n
        .getCollectionOfObjectValues<
          ItemListGetResponse_result_items_prices_deliveries_delivery
        >(createItemListGetResponse_result_items_prices_deliveries_deliveryFromDiscriminatorValue);
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_prices_deliveries_delivery(
  itemListGetResponse_result_items_prices_deliveries_delivery:
    | Partial<ItemListGetResponse_result_items_prices_deliveries_delivery>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "price": (n) => {
      itemListGetResponse_result_items_prices_deliveries_delivery.price = n
        .getStringValue();
    },
    "type": (n) => {
      itemListGetResponse_result_items_prices_deliveries_delivery.type = n
        .getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_review(
  itemListGetResponse_result_items_review:
    | Partial<ItemListGetResponse_result_items_review>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "average": (n) => {
      itemListGetResponse_result_items_review.average = n.getStringValue();
    },
    "count": (n) => {
      itemListGetResponse_result_items_review.count = n.getNumberValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_sampleImageURL(
  itemListGetResponse_result_items_sampleImageURL:
    | Partial<ItemListGetResponse_result_items_sampleImageURL>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "sample_l": (n) => {
      itemListGetResponse_result_items_sampleImageURL.sample_l = n
        .getCollectionOfObjectValues<
          ItemListGetResponse_result_items_sampleImageURL_sample_l
        >(createItemListGetResponse_result_items_sampleImageURL_sample_lFromDiscriminatorValue);
    },
    "sample_s": (n) => {
      itemListGetResponse_result_items_sampleImageURL.sample_s = n
        .getCollectionOfObjectValues<
          ItemListGetResponse_result_items_sampleImageURL_sample_s
        >(createItemListGetResponse_result_items_sampleImageURL_sample_sFromDiscriminatorValue);
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_sampleImageURL_sample_l(
  itemListGetResponse_result_items_sampleImageURL_sample_l:
    | Partial<ItemListGetResponse_result_items_sampleImageURL_sample_l>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "image": (n) => {
      itemListGetResponse_result_items_sampleImageURL_sample_l.image = n
        .getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_sampleImageURL_sample_s(
  itemListGetResponse_result_items_sampleImageURL_sample_s:
    | Partial<ItemListGetResponse_result_items_sampleImageURL_sample_s>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "image": (n) => {
      itemListGetResponse_result_items_sampleImageURL_sample_s.image = n
        .getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_sampleMovieURL(
  itemListGetResponse_result_items_sampleMovieURL:
    | Partial<ItemListGetResponse_result_items_sampleMovieURL>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "pc_flag": (n) => {
      itemListGetResponse_result_items_sampleMovieURL.pc_flag = n
        .getNumberValue();
    },
    "size_476_306": (n) => {
      itemListGetResponse_result_items_sampleMovieURL.size_476_306 = n
        .getStringValue();
    },
    "size_560_360": (n) => {
      itemListGetResponse_result_items_sampleMovieURL.size_560_360 = n
        .getStringValue();
    },
    "size_644_414": (n) => {
      itemListGetResponse_result_items_sampleMovieURL.size_644_414 = n
        .getStringValue();
    },
    "size_720_480": (n) => {
      itemListGetResponse_result_items_sampleMovieURL.size_720_480 = n
        .getStringValue();
    },
    "sp_flag": (n) => {
      itemListGetResponse_result_items_sampleMovieURL.sp_flag = n
        .getNumberValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoItemListGetResponse_result_items_tachiyomi(
  itemListGetResponse_result_items_tachiyomi:
    | Partial<ItemListGetResponse_result_items_tachiyomi>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "affiliateURL": (n) => {
      itemListGetResponse_result_items_tachiyomi.affiliateURL = n
        .getStringValue();
    },
    "URL": (n) => {
      itemListGetResponse_result_items_tachiyomi.uRL = n.getStringValue();
    },
  };
}
export type GetArticleQueryParameterType =
  (typeof GetArticleQueryParameterTypeObject)[
    keyof typeof GetArticleQueryParameterTypeObject
  ];
export type GetMono_stockQueryParameterType =
  (typeof GetMono_stockQueryParameterTypeObject)[
    keyof typeof GetMono_stockQueryParameterTypeObject
  ];
export type GetOutputQueryParameterType =
  (typeof GetOutputQueryParameterTypeObject)[
    keyof typeof GetOutputQueryParameterTypeObject
  ];
export type GetSiteQueryParameterType =
  (typeof GetSiteQueryParameterTypeObject)[
    keyof typeof GetSiteQueryParameterTypeObject
  ];
export type GetSortQueryParameterType =
  (typeof GetSortQueryParameterTypeObject)[
    keyof typeof GetSortQueryParameterTypeObject
  ];
/**
 * DMM.com の商品の情報
 */
export interface ItemListGetResponse extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The request property
   */
  request?: ItemListGetResponse_request;
  /**
   * The result property
   */
  result?: ItemListGetResponse_result;
}
export interface ItemListGetResponse_request
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The parameters property
   */
  parameters?: ItemListGetResponse_request_parameters;
}
export interface ItemListGetResponse_request_parameters
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The affiliate_id property
   */
  affiliate_id?: string;
  /**
   * The api_id property
   */
  api_id?: string;
  /**
   * The floor property
   */
  floor?: string;
  /**
   * The keyword property
   */
  keyword?: string;
  /**
   * The service property
   */
  service?: string;
  /**
   * The site property
   */
  site?: string;
}
export interface ItemListGetResponse_result
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * 検索開始位置
   */
  first_position?: number;
  /**
   * 商品情報
   */
  items?: ItemListGetResponse_result_items[];
  /**
   * 取得件数
   */
  result_count?: number;
  /**
   * ステータスコード
   */
  status?: number;
  /**
   * 全体件数
   */
  total_count?: number;
}
export interface ItemListGetResponse_result_items
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * アフィリエイトリンクURL
   */
  affiliateURL?: string;
  /**
   * キャンペーン情報
   */
  campaign?: ItemListGetResponse_result_items_campaign;
  /**
   * カテゴリ名
   */
  category_name?: string;
  /**
   * CD情報
   */
  cdinfo?: ItemListGetResponse_result_items_cdinfo;
  /**
   * 商品ID
   */
  content_id?: string;
  /**
   * 発売日、配信開始日、貸出開始日
   */
  date?: string;
  /**
   * パンくずリスト
   */
  directory?: ItemListGetResponse_result_items_directory;
  /**
   * フロアコード
   */
  floor_code?: string;
  /**
   * フロア名
   */
  floor_name?: string;
  /**
   * 画像URL
   */
  imageURL?: ItemListGetResponse_result_items_imageURL;
  /**
   * ISBN
   */
  isbn?: string;
  /**
   * 商品詳細
   */
  iteminfo?: ItemListGetResponse_result_items_iteminfo;
  /**
   * JANコード
   */
  jancode?: string;
  /**
   * メーカー品番
   */
  maker_product?: string;
  /**
   * 巻数
   */
  number?: string;
  /**
   * 価格
   */
  prices?: ItemListGetResponse_result_items_prices;
  /**
   * 品番
   */
  product_id?: string;
  /**
   * レビュー平均点
   */
  review?: ItemListGetResponse_result_items_review;
  /**
   * サンプル画像URL
   */
  sampleImageURL?: ItemListGetResponse_result_items_sampleImageURL;
  /**
   * サンプル動画URL
   */
  sampleMovieURL?: ItemListGetResponse_result_items_sampleMovieURL;
  /**
   * サービスコード
   */
  service_code?: string;
  /**
   * サービス名
   */
  service_name?: string;
  /**
   * 在庫状況
   */
  stock?: string;
  /**
   * The tachiyomi property
   */
  tachiyomi?: ItemListGetResponse_result_items_tachiyomi;
  /**
   * タイトル
   */
  title?: string;
  /**
   * 商品ページURL
   */
  uRL?: string;
  /**
   * 収録時間 or ページ数
   */
  volume?: string;
}
/**
 * キャンペーン情報
 */
export interface ItemListGetResponse_result_items_campaign
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * キャンペーン開始日時
   */
  date_begin?: string;
  /**
   * キャンペーン終了日時
   */
  date_end?: string;
  /**
   * キャンペーンタイトル
   */
  title?: string;
}
/**
 * CD情報
 */
export interface ItemListGetResponse_result_items_cdinfo
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * アルバム、シングル
   */
  kind?: string;
}
/**
 * パンくずリスト
 */
export interface ItemListGetResponse_result_items_directory
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * パンくずID
   */
  id?: string;
  /**
   * パンくず名
   */
  name?: string;
}
/**
 * 画像URL
 */
export interface ItemListGetResponse_result_items_imageURL
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * 末端用（大）
   */
  large?: string;
  /**
   * リストページ用
   */
  list?: string;
  /**
   * 末端用（小）
   */
  small?: string;
}
/**
 * 商品詳細
 */
export interface ItemListGetResponse_result_items_iteminfo
  extends AdditionalDataHolder, Parsable {
  /**
   * 出演者（一般作品のみ）
   */
  actor?: ItemListGetResponse_result_items_iteminfo_actor[];
  /**
   * 女優（アダルト作品のみ）
   */
  actress?: ItemListGetResponse_result_items_iteminfo_actress[];
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * 作家、原作者、著者
   */
  author?: ItemListGetResponse_result_items_iteminfo_author[];
  /**
   * カラー
   */
  color?: ItemListGetResponse_result_items_iteminfo_color[];
  /**
   * 監督
   */
  director?: ItemListGetResponse_result_items_iteminfo_director[];
  /**
   * ジャンル
   */
  genre?: ItemListGetResponse_result_items_iteminfo_genre[];
  /**
   * レーベル
   */
  label?: ItemListGetResponse_result_items_iteminfo_label[];
  /**
   * メーカー
   */
  maker?: ItemListGetResponse_result_items_iteminfo_maker[];
  /**
   * 製作
   */
  manufacture?: ItemListGetResponse_result_items_iteminfo_manufacture[];
  /**
   * シリーズ
   */
  series?: ItemListGetResponse_result_items_iteminfo_series[];
  /**
   * サイズ
   */
  size?: ItemListGetResponse_result_items_iteminfo_size[];
  /**
   * タイプ
   */
  type?: ItemListGetResponse_result_items_iteminfo_type[];
}
export interface ItemListGetResponse_result_items_iteminfo_actor
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * 出演者ID
   */
  id?: number;
  /**
   * 出演者名
   */
  name?: string;
}
export interface ItemListGetResponse_result_items_iteminfo_actress
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * 女優ID
   */
  id?: number;
  /**
   * 女優名
   */
  name?: string;
  /**
   * The ruby property
   */
  ruby?: string;
}
export interface ItemListGetResponse_result_items_iteminfo_author
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * 作家、原作者、著者ID
   */
  id?: number;
  /**
   * 作家、原作者、著者名
   */
  name?: string;
}
export interface ItemListGetResponse_result_items_iteminfo_color
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * カラーID
   */
  id?: number;
  /**
   * カラー名
   */
  name?: string;
}
export interface ItemListGetResponse_result_items_iteminfo_director
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * 監督ID
   */
  id?: number;
  /**
   * 監督名
   */
  name?: string;
  /**
   * The ruby property
   */
  ruby?: string;
}
export interface ItemListGetResponse_result_items_iteminfo_genre
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * ジャンルID
   */
  id?: number;
  /**
   * ジャンル名
   */
  name?: string;
}
export interface ItemListGetResponse_result_items_iteminfo_label
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * レーベルID
   */
  id?: number;
  /**
   * レーベル名
   */
  name?: string;
}
export interface ItemListGetResponse_result_items_iteminfo_maker
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * メーカーID
   */
  id?: number;
  /**
   * メーカー名
   */
  name?: string;
}
export interface ItemListGetResponse_result_items_iteminfo_manufacture
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * ID
   */
  id?: number;
  /**
   * 名前
   */
  name?: string;
}
export interface ItemListGetResponse_result_items_iteminfo_series
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * シリーズID
   */
  id?: number;
  /**
   * シリーズ名
   */
  name?: string;
}
export interface ItemListGetResponse_result_items_iteminfo_size
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * サイズID
   */
  id?: number;
  /**
   * サイズ名
   */
  name?: string;
}
export interface ItemListGetResponse_result_items_iteminfo_type
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * タイプID
   */
  id?: number;
  /**
   * タイプ名
   */
  name?: string;
}
/**
 * 価格
 */
export interface ItemListGetResponse_result_items_prices
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * 配信リスト
   */
  deliveries?: ItemListGetResponse_result_items_prices_deliveries;
  /**
   * 定価
   */
  list_price?: string;
  /**
   * 金額
   */
  price?: string;
}
/**
 * 配信リスト
 */
export interface ItemListGetResponse_result_items_prices_deliveries
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * 配信
   */
  delivery?: ItemListGetResponse_result_items_prices_deliveries_delivery[];
}
export interface ItemListGetResponse_result_items_prices_deliveries_delivery
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * 配信価格
   */
  price?: string;
  /**
   * 配信タイプ
   */
  type?: string;
}
/**
 * レビュー平均点
 */
export interface ItemListGetResponse_result_items_review
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * レビュー平均点
   */
  average?: string;
  /**
   * レビュー数
   */
  count?: number;
}
/**
 * サンプル画像URL
 */
export interface ItemListGetResponse_result_items_sampleImageURL
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * サンプル（大）リスト
   */
  sample_l?: ItemListGetResponse_result_items_sampleImageURL_sample_l[];
  /**
   * サンプル（小）リスト
   */
  sample_s?: ItemListGetResponse_result_items_sampleImageURL_sample_s[];
}
export interface ItemListGetResponse_result_items_sampleImageURL_sample_l
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * サンプル画像（大）
   */
  image?: string;
}
export interface ItemListGetResponse_result_items_sampleImageURL_sample_s
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * サンプル画像（小）
   */
  image?: string;
}
/**
 * サンプル動画URL
 */
export interface ItemListGetResponse_result_items_sampleMovieURL
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * PC対応しているか
   */
  pc_flag?: number;
  /**
   * 476×306
   */
  size_476_306?: string;
  /**
   * 560×360
   */
  size_560_360?: string;
  /**
   * 644×414
   */
  size_644_414?: string;
  /**
   * 720×480
   */
  size_720_480?: string;
  /**
   * スマホ対応しているか
   */
  sp_flag?: number;
}
export interface ItemListGetResponse_result_items_tachiyomi
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * 立ち読みアフィリエイトリンクURL
   */
  affiliateURL?: string;
  /**
   * 立ち読みページURL
   */
  uRL?: string;
}
/**
 * Builds and executes requests for operations under /ItemList
 */
export interface ItemListRequestBuilder
  extends BaseRequestBuilder<ItemListRequestBuilder> {
  /**
   * DMM.com の商品の情報を取得することが可能なAPI です。```curlhttps://api.dmm.com/affiliate/v3/AuthorSearch?api_id=[APIID]&affiliate_id=[アフィリエイトID]&iniital=%e3%81%86&floor_id=27&hits=10&output=json```
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {Promise<ItemListGetResponse>}
   */
  get(
    requestConfiguration?:
      | RequestConfiguration<ItemListRequestBuilderGetQueryParameters>
      | undefined,
  ): Promise<ItemListGetResponse | undefined>;
  /**
   * DMM.com の商品の情報を取得することが可能なAPI です。```curlhttps://api.dmm.com/affiliate/v3/AuthorSearch?api_id=[APIID]&affiliate_id=[アフィリエイトID]&iniital=%e3%81%86&floor_id=27&hits=10&output=json```
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {RequestInformation}
   */
  toGetRequestInformation(
    requestConfiguration?:
      | RequestConfiguration<ItemListRequestBuilderGetQueryParameters>
      | undefined,
  ): RequestInformation;
}
/**
 * DMM.com の商品の情報を取得することが可能なAPI です。```curlhttps://api.dmm.com/affiliate/v3/AuthorSearch?api_id=[APIID]&affiliate_id=[アフィリエイトID]&iniital=%e3%81%86&floor_id=27&hits=10&output=json```
 */
export interface ItemListRequestBuilderGetQueryParameters {
  /**
   * 絞りこみ項目 女優：actress 作者：author ジャンル：genre シリーズ：series メーカー：maker
   */
  article?: GetArticleQueryParameterType;
  /**
   * 絞り込みID 上記絞り込み項目のID(各検索APIから取得可能)
   */
  articleId?: string;
  /**
   * 出力形式jsonで指定した場合に、このパラメータでコールバック関数名を指定すると、JSONP形式で出力されます
   */
  callback?: string;
  /**
   * 商品ID 商品に振られているcontent_id
   */
  cid?: string;
  /**
   * フロアAPIから取得できるフロアコードを指定
   */
  floor?: string;
  /**
   * 発売日絞り込み このパラメータで指定した日付以降に発売された商品を絞り込むことができます。 ISO8601形式でフォーマットした日付を指定してください。(ただし、タイムゾーンは指定できません)
   */
  gteDate?: Date;
  /**
   * 取得件数 初期値：20　最大：100
   */
  hits?: number;
  /**
   * キーワード UTF-8で指定
   */
  keyword?: string;
  /**
   * 発売日絞り込み このパラメータで指定した日付以前に発売された商品を絞り込むことができます。 フォーマットはgte_dateと同じです。
   */
  lteDate?: Date;
  /**
   * 在庫絞り込み 初期値：絞り込みなし 在庫あり：stock 予約商品（在庫あり）：reserve 予約商品（キャンセル待ち）：reserve_empty DMM通販のみ：mono マーケットプレイスのみ：dmp ※通販サービスのみ指定可能
   */
  monoStock?: GetMono_stockQueryParameterType;
  /**
   * 検索開始位置 初期値：1　最大：50000
   */
  offset?: number;
  /**
   * 出力形式
   */
  output?: GetOutputQueryParameterType;
  /**
   * フロアAPIから取得できるサービスコードを指定
   */
  service?: string;
  /**
   * 一般（DMM.com）かアダルト（FANZA）か
   */
  site?: GetSiteQueryParameterType;
  /**
   * ソート順 初期値：rank 人気：rank 価格が高い順：price 価格が安い順：-price 新着：date 評価：review マッチング順：match
   */
  sort?: GetSortQueryParameterType;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse(
  writer: SerializationWriter,
  itemListGetResponse: Partial<ItemListGetResponse> | undefined = {},
): void {
  writer.writeObjectValue<ItemListGetResponse_request>(
    "request",
    itemListGetResponse.request,
    serializeItemListGetResponse_request,
  );
  writer.writeObjectValue<ItemListGetResponse_result>(
    "result",
    itemListGetResponse.result,
    serializeItemListGetResponse_result,
  );
  writer.writeAdditionalData(itemListGetResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_request(
  writer: SerializationWriter,
  itemListGetResponse_request:
    | Partial<ItemListGetResponse_request>
    | undefined = {},
): void {
  writer.writeObjectValue<ItemListGetResponse_request_parameters>(
    "parameters",
    itemListGetResponse_request.parameters,
    serializeItemListGetResponse_request_parameters,
  );
  writer.writeAdditionalData(itemListGetResponse_request.additionalData);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_request_parameters(
  writer: SerializationWriter,
  itemListGetResponse_request_parameters:
    | Partial<ItemListGetResponse_request_parameters>
    | undefined = {},
): void {
  writer.writeStringValue(
    "affiliate_id",
    itemListGetResponse_request_parameters.affiliate_id,
  );
  writer.writeStringValue(
    "api_id",
    itemListGetResponse_request_parameters.api_id,
  );
  writer.writeStringValue(
    "floor",
    itemListGetResponse_request_parameters.floor,
  );
  writer.writeStringValue(
    "keyword",
    itemListGetResponse_request_parameters.keyword,
  );
  writer.writeStringValue(
    "service",
    itemListGetResponse_request_parameters.service,
  );
  writer.writeStringValue("site", itemListGetResponse_request_parameters.site);
  writer.writeAdditionalData(
    itemListGetResponse_request_parameters.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result(
  writer: SerializationWriter,
  itemListGetResponse_result: Partial<ItemListGetResponse_result> | undefined =
    {},
): void {
  writer.writeNumberValue(
    "first_position",
    itemListGetResponse_result.first_position,
  );
  writer.writeCollectionOfObjectValues<ItemListGetResponse_result_items>(
    "items",
    itemListGetResponse_result.items,
    serializeItemListGetResponse_result_items,
  );
  writer.writeNumberValue(
    "result_count",
    itemListGetResponse_result.result_count,
  );
  writer.writeNumberValue("status", itemListGetResponse_result.status);
  writer.writeNumberValue(
    "total_count",
    itemListGetResponse_result.total_count,
  );
  writer.writeAdditionalData(itemListGetResponse_result.additionalData);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items(
  writer: SerializationWriter,
  itemListGetResponse_result_items:
    | Partial<ItemListGetResponse_result_items>
    | undefined = {},
): void {
  writer.writeStringValue(
    "affiliateURL",
    itemListGetResponse_result_items.affiliateURL,
  );
  writer.writeObjectValue<ItemListGetResponse_result_items_campaign>(
    "campaign",
    itemListGetResponse_result_items.campaign,
    serializeItemListGetResponse_result_items_campaign,
  );
  writer.writeStringValue(
    "category_name",
    itemListGetResponse_result_items.category_name,
  );
  writer.writeObjectValue<ItemListGetResponse_result_items_cdinfo>(
    "cdinfo",
    itemListGetResponse_result_items.cdinfo,
    serializeItemListGetResponse_result_items_cdinfo,
  );
  writer.writeStringValue(
    "content_id",
    itemListGetResponse_result_items.content_id,
  );
  writer.writeStringValue("date", itemListGetResponse_result_items.date);
  writer.writeObjectValue<ItemListGetResponse_result_items_directory>(
    "directory",
    itemListGetResponse_result_items.directory,
    serializeItemListGetResponse_result_items_directory,
  );
  writer.writeStringValue(
    "floor_code",
    itemListGetResponse_result_items.floor_code,
  );
  writer.writeStringValue(
    "floor_name",
    itemListGetResponse_result_items.floor_name,
  );
  writer.writeObjectValue<ItemListGetResponse_result_items_imageURL>(
    "imageURL",
    itemListGetResponse_result_items.imageURL,
    serializeItemListGetResponse_result_items_imageURL,
  );
  writer.writeStringValue("isbn", itemListGetResponse_result_items.isbn);
  writer.writeObjectValue<ItemListGetResponse_result_items_iteminfo>(
    "iteminfo",
    itemListGetResponse_result_items.iteminfo,
    serializeItemListGetResponse_result_items_iteminfo,
  );
  writer.writeStringValue("jancode", itemListGetResponse_result_items.jancode);
  writer.writeStringValue(
    "maker_product",
    itemListGetResponse_result_items.maker_product,
  );
  writer.writeStringValue("number", itemListGetResponse_result_items.number);
  writer.writeObjectValue<ItemListGetResponse_result_items_prices>(
    "prices",
    itemListGetResponse_result_items.prices,
    serializeItemListGetResponse_result_items_prices,
  );
  writer.writeStringValue(
    "product_id",
    itemListGetResponse_result_items.product_id,
  );
  writer.writeObjectValue<ItemListGetResponse_result_items_review>(
    "review",
    itemListGetResponse_result_items.review,
    serializeItemListGetResponse_result_items_review,
  );
  writer.writeObjectValue<ItemListGetResponse_result_items_sampleImageURL>(
    "sampleImageURL",
    itemListGetResponse_result_items.sampleImageURL,
    serializeItemListGetResponse_result_items_sampleImageURL,
  );
  writer.writeObjectValue<ItemListGetResponse_result_items_sampleMovieURL>(
    "sampleMovieURL",
    itemListGetResponse_result_items.sampleMovieURL,
    serializeItemListGetResponse_result_items_sampleMovieURL,
  );
  writer.writeStringValue(
    "service_code",
    itemListGetResponse_result_items.service_code,
  );
  writer.writeStringValue(
    "service_name",
    itemListGetResponse_result_items.service_name,
  );
  writer.writeStringValue("stock", itemListGetResponse_result_items.stock);
  writer.writeObjectValue<ItemListGetResponse_result_items_tachiyomi>(
    "tachiyomi",
    itemListGetResponse_result_items.tachiyomi,
    serializeItemListGetResponse_result_items_tachiyomi,
  );
  writer.writeStringValue("title", itemListGetResponse_result_items.title);
  writer.writeStringValue("URL", itemListGetResponse_result_items.uRL);
  writer.writeStringValue("volume", itemListGetResponse_result_items.volume);
  writer.writeAdditionalData(itemListGetResponse_result_items.additionalData);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_campaign(
  writer: SerializationWriter,
  itemListGetResponse_result_items_campaign:
    | Partial<ItemListGetResponse_result_items_campaign>
    | undefined = {},
): void {
  writer.writeStringValue(
    "date_begin",
    itemListGetResponse_result_items_campaign.date_begin,
  );
  writer.writeStringValue(
    "date_end",
    itemListGetResponse_result_items_campaign.date_end,
  );
  writer.writeStringValue(
    "title",
    itemListGetResponse_result_items_campaign.title,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_campaign.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_cdinfo(
  writer: SerializationWriter,
  itemListGetResponse_result_items_cdinfo:
    | Partial<ItemListGetResponse_result_items_cdinfo>
    | undefined = {},
): void {
  writer.writeStringValue("kind", itemListGetResponse_result_items_cdinfo.kind);
  writer.writeAdditionalData(
    itemListGetResponse_result_items_cdinfo.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_directory(
  writer: SerializationWriter,
  itemListGetResponse_result_items_directory:
    | Partial<ItemListGetResponse_result_items_directory>
    | undefined = {},
): void {
  writer.writeStringValue("id", itemListGetResponse_result_items_directory.id);
  writer.writeStringValue(
    "name",
    itemListGetResponse_result_items_directory.name,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_directory.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_imageURL(
  writer: SerializationWriter,
  itemListGetResponse_result_items_imageURL:
    | Partial<ItemListGetResponse_result_items_imageURL>
    | undefined = {},
): void {
  writer.writeStringValue(
    "large",
    itemListGetResponse_result_items_imageURL.large,
  );
  writer.writeStringValue(
    "list",
    itemListGetResponse_result_items_imageURL.list,
  );
  writer.writeStringValue(
    "small",
    itemListGetResponse_result_items_imageURL.small,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_imageURL.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_iteminfo(
  writer: SerializationWriter,
  itemListGetResponse_result_items_iteminfo:
    | Partial<ItemListGetResponse_result_items_iteminfo>
    | undefined = {},
): void {
  writer.writeCollectionOfObjectValues<
    ItemListGetResponse_result_items_iteminfo_actor
  >(
    "actor",
    itemListGetResponse_result_items_iteminfo.actor,
    serializeItemListGetResponse_result_items_iteminfo_actor,
  );
  writer.writeCollectionOfObjectValues<
    ItemListGetResponse_result_items_iteminfo_actress
  >(
    "actress",
    itemListGetResponse_result_items_iteminfo.actress,
    serializeItemListGetResponse_result_items_iteminfo_actress,
  );
  writer.writeCollectionOfObjectValues<
    ItemListGetResponse_result_items_iteminfo_author
  >(
    "author",
    itemListGetResponse_result_items_iteminfo.author,
    serializeItemListGetResponse_result_items_iteminfo_author,
  );
  writer.writeCollectionOfObjectValues<
    ItemListGetResponse_result_items_iteminfo_color
  >(
    "color",
    itemListGetResponse_result_items_iteminfo.color,
    serializeItemListGetResponse_result_items_iteminfo_color,
  );
  writer.writeCollectionOfObjectValues<
    ItemListGetResponse_result_items_iteminfo_director
  >(
    "director",
    itemListGetResponse_result_items_iteminfo.director,
    serializeItemListGetResponse_result_items_iteminfo_director,
  );
  writer.writeCollectionOfObjectValues<
    ItemListGetResponse_result_items_iteminfo_genre
  >(
    "genre",
    itemListGetResponse_result_items_iteminfo.genre,
    serializeItemListGetResponse_result_items_iteminfo_genre,
  );
  writer.writeCollectionOfObjectValues<
    ItemListGetResponse_result_items_iteminfo_label
  >(
    "label",
    itemListGetResponse_result_items_iteminfo.label,
    serializeItemListGetResponse_result_items_iteminfo_label,
  );
  writer.writeCollectionOfObjectValues<
    ItemListGetResponse_result_items_iteminfo_maker
  >(
    "maker",
    itemListGetResponse_result_items_iteminfo.maker,
    serializeItemListGetResponse_result_items_iteminfo_maker,
  );
  writer.writeCollectionOfObjectValues<
    ItemListGetResponse_result_items_iteminfo_manufacture
  >(
    "manufacture",
    itemListGetResponse_result_items_iteminfo.manufacture,
    serializeItemListGetResponse_result_items_iteminfo_manufacture,
  );
  writer.writeCollectionOfObjectValues<
    ItemListGetResponse_result_items_iteminfo_series
  >(
    "series",
    itemListGetResponse_result_items_iteminfo.series,
    serializeItemListGetResponse_result_items_iteminfo_series,
  );
  writer.writeCollectionOfObjectValues<
    ItemListGetResponse_result_items_iteminfo_size
  >(
    "size",
    itemListGetResponse_result_items_iteminfo.size,
    serializeItemListGetResponse_result_items_iteminfo_size,
  );
  writer.writeCollectionOfObjectValues<
    ItemListGetResponse_result_items_iteminfo_type
  >(
    "type",
    itemListGetResponse_result_items_iteminfo.type,
    serializeItemListGetResponse_result_items_iteminfo_type,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_iteminfo.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_iteminfo_actor(
  writer: SerializationWriter,
  itemListGetResponse_result_items_iteminfo_actor:
    | Partial<ItemListGetResponse_result_items_iteminfo_actor>
    | undefined = {},
): void {
  writer.writeNumberValue(
    "id",
    itemListGetResponse_result_items_iteminfo_actor.id,
  );
  writer.writeStringValue(
    "name",
    itemListGetResponse_result_items_iteminfo_actor.name,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_iteminfo_actor.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_iteminfo_actress(
  writer: SerializationWriter,
  itemListGetResponse_result_items_iteminfo_actress:
    | Partial<ItemListGetResponse_result_items_iteminfo_actress>
    | undefined = {},
): void {
  writer.writeNumberValue(
    "id",
    itemListGetResponse_result_items_iteminfo_actress.id,
  );
  writer.writeStringValue(
    "name",
    itemListGetResponse_result_items_iteminfo_actress.name,
  );
  writer.writeStringValue(
    "ruby",
    itemListGetResponse_result_items_iteminfo_actress.ruby,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_iteminfo_actress.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_iteminfo_author(
  writer: SerializationWriter,
  itemListGetResponse_result_items_iteminfo_author:
    | Partial<ItemListGetResponse_result_items_iteminfo_author>
    | undefined = {},
): void {
  writer.writeNumberValue(
    "id",
    itemListGetResponse_result_items_iteminfo_author.id,
  );
  writer.writeStringValue(
    "name",
    itemListGetResponse_result_items_iteminfo_author.name,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_iteminfo_author.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_iteminfo_color(
  writer: SerializationWriter,
  itemListGetResponse_result_items_iteminfo_color:
    | Partial<ItemListGetResponse_result_items_iteminfo_color>
    | undefined = {},
): void {
  writer.writeNumberValue(
    "id",
    itemListGetResponse_result_items_iteminfo_color.id,
  );
  writer.writeStringValue(
    "name",
    itemListGetResponse_result_items_iteminfo_color.name,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_iteminfo_color.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_iteminfo_director(
  writer: SerializationWriter,
  itemListGetResponse_result_items_iteminfo_director:
    | Partial<ItemListGetResponse_result_items_iteminfo_director>
    | undefined = {},
): void {
  writer.writeNumberValue(
    "id",
    itemListGetResponse_result_items_iteminfo_director.id,
  );
  writer.writeStringValue(
    "name",
    itemListGetResponse_result_items_iteminfo_director.name,
  );
  writer.writeStringValue(
    "ruby",
    itemListGetResponse_result_items_iteminfo_director.ruby,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_iteminfo_director.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_iteminfo_genre(
  writer: SerializationWriter,
  itemListGetResponse_result_items_iteminfo_genre:
    | Partial<ItemListGetResponse_result_items_iteminfo_genre>
    | undefined = {},
): void {
  writer.writeNumberValue(
    "id",
    itemListGetResponse_result_items_iteminfo_genre.id,
  );
  writer.writeStringValue(
    "name",
    itemListGetResponse_result_items_iteminfo_genre.name,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_iteminfo_genre.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_iteminfo_label(
  writer: SerializationWriter,
  itemListGetResponse_result_items_iteminfo_label:
    | Partial<ItemListGetResponse_result_items_iteminfo_label>
    | undefined = {},
): void {
  writer.writeNumberValue(
    "id",
    itemListGetResponse_result_items_iteminfo_label.id,
  );
  writer.writeStringValue(
    "name",
    itemListGetResponse_result_items_iteminfo_label.name,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_iteminfo_label.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_iteminfo_maker(
  writer: SerializationWriter,
  itemListGetResponse_result_items_iteminfo_maker:
    | Partial<ItemListGetResponse_result_items_iteminfo_maker>
    | undefined = {},
): void {
  writer.writeNumberValue(
    "id",
    itemListGetResponse_result_items_iteminfo_maker.id,
  );
  writer.writeStringValue(
    "name",
    itemListGetResponse_result_items_iteminfo_maker.name,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_iteminfo_maker.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_iteminfo_manufacture(
  writer: SerializationWriter,
  itemListGetResponse_result_items_iteminfo_manufacture:
    | Partial<ItemListGetResponse_result_items_iteminfo_manufacture>
    | undefined = {},
): void {
  writer.writeNumberValue(
    "id",
    itemListGetResponse_result_items_iteminfo_manufacture.id,
  );
  writer.writeStringValue(
    "name",
    itemListGetResponse_result_items_iteminfo_manufacture.name,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_iteminfo_manufacture.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_iteminfo_series(
  writer: SerializationWriter,
  itemListGetResponse_result_items_iteminfo_series:
    | Partial<ItemListGetResponse_result_items_iteminfo_series>
    | undefined = {},
): void {
  writer.writeNumberValue(
    "id",
    itemListGetResponse_result_items_iteminfo_series.id,
  );
  writer.writeStringValue(
    "name",
    itemListGetResponse_result_items_iteminfo_series.name,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_iteminfo_series.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_iteminfo_size(
  writer: SerializationWriter,
  itemListGetResponse_result_items_iteminfo_size:
    | Partial<ItemListGetResponse_result_items_iteminfo_size>
    | undefined = {},
): void {
  writer.writeNumberValue(
    "id",
    itemListGetResponse_result_items_iteminfo_size.id,
  );
  writer.writeStringValue(
    "name",
    itemListGetResponse_result_items_iteminfo_size.name,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_iteminfo_size.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_iteminfo_type(
  writer: SerializationWriter,
  itemListGetResponse_result_items_iteminfo_type:
    | Partial<ItemListGetResponse_result_items_iteminfo_type>
    | undefined = {},
): void {
  writer.writeNumberValue(
    "id",
    itemListGetResponse_result_items_iteminfo_type.id,
  );
  writer.writeStringValue(
    "name",
    itemListGetResponse_result_items_iteminfo_type.name,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_iteminfo_type.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_prices(
  writer: SerializationWriter,
  itemListGetResponse_result_items_prices:
    | Partial<ItemListGetResponse_result_items_prices>
    | undefined = {},
): void {
  writer.writeObjectValue<ItemListGetResponse_result_items_prices_deliveries>(
    "deliveries",
    itemListGetResponse_result_items_prices.deliveries,
    serializeItemListGetResponse_result_items_prices_deliveries,
  );
  writer.writeStringValue(
    "list_price",
    itemListGetResponse_result_items_prices.list_price,
  );
  writer.writeStringValue(
    "price",
    itemListGetResponse_result_items_prices.price,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_prices.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_prices_deliveries(
  writer: SerializationWriter,
  itemListGetResponse_result_items_prices_deliveries:
    | Partial<ItemListGetResponse_result_items_prices_deliveries>
    | undefined = {},
): void {
  writer.writeCollectionOfObjectValues<
    ItemListGetResponse_result_items_prices_deliveries_delivery
  >(
    "delivery",
    itemListGetResponse_result_items_prices_deliveries.delivery,
    serializeItemListGetResponse_result_items_prices_deliveries_delivery,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_prices_deliveries.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_prices_deliveries_delivery(
  writer: SerializationWriter,
  itemListGetResponse_result_items_prices_deliveries_delivery:
    | Partial<ItemListGetResponse_result_items_prices_deliveries_delivery>
    | undefined = {},
): void {
  writer.writeStringValue(
    "price",
    itemListGetResponse_result_items_prices_deliveries_delivery.price,
  );
  writer.writeStringValue(
    "type",
    itemListGetResponse_result_items_prices_deliveries_delivery.type,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_prices_deliveries_delivery.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_review(
  writer: SerializationWriter,
  itemListGetResponse_result_items_review:
    | Partial<ItemListGetResponse_result_items_review>
    | undefined = {},
): void {
  writer.writeStringValue(
    "average",
    itemListGetResponse_result_items_review.average,
  );
  writer.writeNumberValue(
    "count",
    itemListGetResponse_result_items_review.count,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_review.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_sampleImageURL(
  writer: SerializationWriter,
  itemListGetResponse_result_items_sampleImageURL:
    | Partial<ItemListGetResponse_result_items_sampleImageURL>
    | undefined = {},
): void {
  writer.writeCollectionOfObjectValues<
    ItemListGetResponse_result_items_sampleImageURL_sample_l
  >(
    "sample_l",
    itemListGetResponse_result_items_sampleImageURL.sample_l,
    serializeItemListGetResponse_result_items_sampleImageURL_sample_l,
  );
  writer.writeCollectionOfObjectValues<
    ItemListGetResponse_result_items_sampleImageURL_sample_s
  >(
    "sample_s",
    itemListGetResponse_result_items_sampleImageURL.sample_s,
    serializeItemListGetResponse_result_items_sampleImageURL_sample_s,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_sampleImageURL.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_sampleImageURL_sample_l(
  writer: SerializationWriter,
  itemListGetResponse_result_items_sampleImageURL_sample_l:
    | Partial<ItemListGetResponse_result_items_sampleImageURL_sample_l>
    | undefined = {},
): void {
  writer.writeStringValue(
    "image",
    itemListGetResponse_result_items_sampleImageURL_sample_l.image,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_sampleImageURL_sample_l.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_sampleImageURL_sample_s(
  writer: SerializationWriter,
  itemListGetResponse_result_items_sampleImageURL_sample_s:
    | Partial<ItemListGetResponse_result_items_sampleImageURL_sample_s>
    | undefined = {},
): void {
  writer.writeStringValue(
    "image",
    itemListGetResponse_result_items_sampleImageURL_sample_s.image,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_sampleImageURL_sample_s.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_sampleMovieURL(
  writer: SerializationWriter,
  itemListGetResponse_result_items_sampleMovieURL:
    | Partial<ItemListGetResponse_result_items_sampleMovieURL>
    | undefined = {},
): void {
  writer.writeNumberValue(
    "pc_flag",
    itemListGetResponse_result_items_sampleMovieURL.pc_flag,
  );
  writer.writeStringValue(
    "size_476_306",
    itemListGetResponse_result_items_sampleMovieURL.size_476_306,
  );
  writer.writeStringValue(
    "size_560_360",
    itemListGetResponse_result_items_sampleMovieURL.size_560_360,
  );
  writer.writeStringValue(
    "size_644_414",
    itemListGetResponse_result_items_sampleMovieURL.size_644_414,
  );
  writer.writeStringValue(
    "size_720_480",
    itemListGetResponse_result_items_sampleMovieURL.size_720_480,
  );
  writer.writeNumberValue(
    "sp_flag",
    itemListGetResponse_result_items_sampleMovieURL.sp_flag,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_sampleMovieURL.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeItemListGetResponse_result_items_tachiyomi(
  writer: SerializationWriter,
  itemListGetResponse_result_items_tachiyomi:
    | Partial<ItemListGetResponse_result_items_tachiyomi>
    | undefined = {},
): void {
  writer.writeStringValue(
    "affiliateURL",
    itemListGetResponse_result_items_tachiyomi.affiliateURL,
  );
  writer.writeStringValue(
    "URL",
    itemListGetResponse_result_items_tachiyomi.uRL,
  );
  writer.writeAdditionalData(
    itemListGetResponse_result_items_tachiyomi.additionalData,
  );
}
/**
 * Uri template for the request builder.
 */
export const ItemListRequestBuilderUriTemplate =
  "{+baseurl}/ItemList?site={site}{&article*,article_id*,callback*,cid*,floor*,gte_date*,hits*,keyword*,lte_date*,mono_stock*,offset*,output*,service*,sort*}";
export const GetArticleQueryParameterTypeObject = {
  Actress: "actress",
  Author: "author",
  Genre: "genre",
  Series: "series",
  Maker: "maker",
} as const;
export const GetMono_stockQueryParameterTypeObject = {
  Stock: "stock",
  Reserve: "reserve",
  Reserve_empty: "reserve_empty",
  Mono: "mono",
  Dmp: "dmp",
} as const;
export const GetOutputQueryParameterTypeObject = {
  Json: "json",
  Xml: "xml",
} as const;
export const GetSiteQueryParameterTypeObject = {
  DMMCom: "DMM.com",
  FANZA: "FANZA",
} as const;
export const GetSortQueryParameterTypeObject = {
  Rank: "rank",
  Price: "price",
  Minus_price: "-price",
  Date: "date",
  Review: "review",
  Match: "match",
} as const;
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const ItemListRequestBuilderGetQueryParametersMapper: Record<string, string> = {
  "articleId": "article_id",
  "gteDate": "gte_date",
  "lteDate": "lte_date",
  "monoStock": "mono_stock",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ItemListRequestBuilderRequestsMetadata: RequestsMetadata = {
  get: {
    uriTemplate: ItemListRequestBuilderUriTemplate,
    responseBodyContentType: "application/json",
    adapterMethodName: "send",
    responseBodyFactory: createItemListGetResponseFromDiscriminatorValue,
    queryParametersMapper: ItemListRequestBuilderGetQueryParametersMapper,
  },
};
/* tslint:enable */
/* eslint-enable */
