/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
  type AdditionalDataHolder,
  type BaseRequestBuilder,
  type Parsable,
  type ParsableFactory,
  type ParseNode,
  type RequestConfiguration,
  type RequestInformation,
  type RequestsMetadata,
  type SerializationWriter,
} from "@microsoft/kiota-abstractions";

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FloorListGetResponse_request_parameters}
 */
// @ts-ignore
export function createFloorListGetResponse_request_parametersFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoFloorListGetResponse_request_parameters;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FloorListGetResponse_request}
 */
// @ts-ignore
export function createFloorListGetResponse_requestFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoFloorListGetResponse_request;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FloorListGetResponse_result_site_service_floor}
 */
// @ts-ignore
export function createFloorListGetResponse_result_site_service_floorFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoFloorListGetResponse_result_site_service_floor;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FloorListGetResponse_result_site_service}
 */
// @ts-ignore
export function createFloorListGetResponse_result_site_serviceFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoFloorListGetResponse_result_site_service;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FloorListGetResponse_result_site}
 */
// @ts-ignore
export function createFloorListGetResponse_result_siteFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoFloorListGetResponse_result_site;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FloorListGetResponse_result}
 */
// @ts-ignore
export function createFloorListGetResponse_resultFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoFloorListGetResponse_result;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FloorListGetResponse}
 */
// @ts-ignore
export function createFloorListGetResponseFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoFloorListGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFloorListGetResponse(
  floorListGetResponse: Partial<FloorListGetResponse> | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "request": (n) => {
      floorListGetResponse.request = n.getObjectValue<
        FloorListGetResponse_request
      >(createFloorListGetResponse_requestFromDiscriminatorValue);
    },
    "result": (n) => {
      floorListGetResponse.result = n.getObjectValue<
        FloorListGetResponse_result
      >(createFloorListGetResponse_resultFromDiscriminatorValue);
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFloorListGetResponse_request(
  floorListGetResponse_request:
    | Partial<FloorListGetResponse_request>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "parameters": (n) => {
      floorListGetResponse_request.parameters = n.getObjectValue<
        FloorListGetResponse_request_parameters
      >(createFloorListGetResponse_request_parametersFromDiscriminatorValue);
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFloorListGetResponse_request_parameters(
  floorListGetResponse_request_parameters:
    | Partial<FloorListGetResponse_request_parameters>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "affiliate_id": (n) => {
      floorListGetResponse_request_parameters.affiliate_id = n.getStringValue();
    },
    "api_id": (n) => {
      floorListGetResponse_request_parameters.api_id = n.getStringValue();
    },
    "callback": (n) => {
      floorListGetResponse_request_parameters.callback = n.getStringValue();
    },
    "output": (n) => {
      floorListGetResponse_request_parameters.output = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFloorListGetResponse_result(
  floorListGetResponse_result:
    | Partial<FloorListGetResponse_result>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "site": (n) => {
      floorListGetResponse_result.site = n.getCollectionOfObjectValues<
        FloorListGetResponse_result_site
      >(createFloorListGetResponse_result_siteFromDiscriminatorValue);
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFloorListGetResponse_result_site(
  floorListGetResponse_result_site:
    | Partial<FloorListGetResponse_result_site>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "code": (n) => {
      floorListGetResponse_result_site.code = n.getStringValue();
    },
    "name": (n) => {
      floorListGetResponse_result_site.name = n.getStringValue();
    },
    "service": (n) => {
      floorListGetResponse_result_site.service = n.getCollectionOfObjectValues<
        FloorListGetResponse_result_site_service
      >(createFloorListGetResponse_result_site_serviceFromDiscriminatorValue);
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFloorListGetResponse_result_site_service(
  floorListGetResponse_result_site_service:
    | Partial<FloorListGetResponse_result_site_service>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "code": (n) => {
      floorListGetResponse_result_site_service.code = n.getStringValue();
    },
    "floor": (n) => {
      floorListGetResponse_result_site_service.floor = n
        .getCollectionOfObjectValues<
          FloorListGetResponse_result_site_service_floor
        >(createFloorListGetResponse_result_site_service_floorFromDiscriminatorValue);
    },
    "name": (n) => {
      floorListGetResponse_result_site_service.name = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFloorListGetResponse_result_site_service_floor(
  floorListGetResponse_result_site_service_floor:
    | Partial<FloorListGetResponse_result_site_service_floor>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "code": (n) => {
      floorListGetResponse_result_site_service_floor.code = n.getStringValue();
    },
    "id": (n) => {
      floorListGetResponse_result_site_service_floor.id = n.getStringValue();
    },
    "name": (n) => {
      floorListGetResponse_result_site_service_floor.name = n.getStringValue();
    },
  };
}
/**
 * フロア一覧
 */
export interface FloorListGetResponse extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The request property
   */
  request?: FloorListGetResponse_request | null;
  /**
   * The result property
   */
  result?: FloorListGetResponse_result | null;
}
export interface FloorListGetResponse_request
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The parameters property
   */
  parameters?: FloorListGetResponse_request_parameters | null;
}
export interface FloorListGetResponse_request_parameters
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The affiliate_id property
   */
  affiliate_id?: string | null;
  /**
   * The api_id property
   */
  api_id?: string | null;
  /**
   * The callback property
   */
  callback?: string | null;
  /**
   * The output property
   */
  output?: string | null;
}
export interface FloorListGetResponse_result
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The site property
   */
  site?: FloorListGetResponse_result_site[] | null;
}
export interface FloorListGetResponse_result_site
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The code property
   */
  code?: string | null;
  /**
   * The name property
   */
  name?: string | null;
  /**
   * The service property
   */
  service?: FloorListGetResponse_result_site_service[] | null;
}
export interface FloorListGetResponse_result_site_service
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The code property
   */
  code?: string | null;
  /**
   * The floor property
   */
  floor?: FloorListGetResponse_result_site_service_floor[] | null;
  /**
   * The name property
   */
  name?: string | null;
}
export interface FloorListGetResponse_result_site_service_floor
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The code property
   */
  code?: string | null;
  /**
   * The id property
   */
  id?: string | null;
  /**
   * The name property
   */
  name?: string | null;
}
/**
 * Builds and executes requests for operations under /FloorList
 */
export interface FloorListRequestBuilder
  extends BaseRequestBuilder<FloorListRequestBuilder> {
  /**
   * フロア一覧を取得することが可能なAPIです。```curlhttps://api.dmm.com/affiliate/v3/FloorList?api_id=[APIID]&affiliate_id=[アフィリエイトID]&output=json&callback=example```
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {Promise<FloorListGetResponse>}
   */
  get(
    requestConfiguration?:
      | RequestConfiguration<FloorListRequestBuilderGetQueryParameters>
      | undefined,
  ): Promise<FloorListGetResponse | undefined>;
  /**
   * フロア一覧を取得することが可能なAPIです。```curlhttps://api.dmm.com/affiliate/v3/FloorList?api_id=[APIID]&affiliate_id=[アフィリエイトID]&output=json&callback=example```
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {RequestInformation}
   */
  toGetRequestInformation(
    requestConfiguration?:
      | RequestConfiguration<FloorListRequestBuilderGetQueryParameters>
      | undefined,
  ): RequestInformation;
}
/**
 * フロア一覧を取得することが可能なAPIです。```curlhttps://api.dmm.com/affiliate/v3/FloorList?api_id=[APIID]&affiliate_id=[アフィリエイトID]&output=json&callback=example```
 */
export interface FloorListRequestBuilderGetQueryParameters {
  /**
   * 出力形式jsonで指定した場合に、このパラメータでコールバック関数名を指定すると、JSONP形式で出力されます
   */
  callback?: string;
  /**
   * 出力形式
   */
  output?: GetOutputQueryParameterType;
}
export type GetOutputQueryParameterType =
  (typeof GetOutputQueryParameterTypeObject)[
    keyof typeof GetOutputQueryParameterTypeObject
  ];
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFloorListGetResponse(
  writer: SerializationWriter,
  floorListGetResponse: Partial<FloorListGetResponse> | undefined | null = {},
): void {
  if (floorListGetResponse) {
    writer.writeObjectValue<FloorListGetResponse_request>(
      "request",
      floorListGetResponse.request,
      serializeFloorListGetResponse_request,
    );
    writer.writeObjectValue<FloorListGetResponse_result>(
      "result",
      floorListGetResponse.result,
      serializeFloorListGetResponse_result,
    );
    writer.writeAdditionalData(floorListGetResponse.additionalData);
  }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFloorListGetResponse_request(
  writer: SerializationWriter,
  floorListGetResponse_request:
    | Partial<FloorListGetResponse_request>
    | undefined
    | null = {},
): void {
  if (floorListGetResponse_request) {
    writer.writeObjectValue<FloorListGetResponse_request_parameters>(
      "parameters",
      floorListGetResponse_request.parameters,
      serializeFloorListGetResponse_request_parameters,
    );
    writer.writeAdditionalData(floorListGetResponse_request.additionalData);
  }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFloorListGetResponse_request_parameters(
  writer: SerializationWriter,
  floorListGetResponse_request_parameters:
    | Partial<FloorListGetResponse_request_parameters>
    | undefined
    | null = {},
): void {
  if (floorListGetResponse_request_parameters) {
    writer.writeStringValue(
      "affiliate_id",
      floorListGetResponse_request_parameters.affiliate_id,
    );
    writer.writeStringValue(
      "api_id",
      floorListGetResponse_request_parameters.api_id,
    );
    writer.writeStringValue(
      "callback",
      floorListGetResponse_request_parameters.callback,
    );
    writer.writeStringValue(
      "output",
      floorListGetResponse_request_parameters.output,
    );
    writer.writeAdditionalData(
      floorListGetResponse_request_parameters.additionalData,
    );
  }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFloorListGetResponse_result(
  writer: SerializationWriter,
  floorListGetResponse_result:
    | Partial<FloorListGetResponse_result>
    | undefined
    | null = {},
): void {
  if (floorListGetResponse_result) {
    writer.writeCollectionOfObjectValues<FloorListGetResponse_result_site>(
      "site",
      floorListGetResponse_result.site,
      serializeFloorListGetResponse_result_site,
    );
    writer.writeAdditionalData(floorListGetResponse_result.additionalData);
  }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFloorListGetResponse_result_site(
  writer: SerializationWriter,
  floorListGetResponse_result_site:
    | Partial<FloorListGetResponse_result_site>
    | undefined
    | null = {},
): void {
  if (floorListGetResponse_result_site) {
    writer.writeStringValue("code", floorListGetResponse_result_site.code);
    writer.writeStringValue("name", floorListGetResponse_result_site.name);
    writer.writeCollectionOfObjectValues<
      FloorListGetResponse_result_site_service
    >(
      "service",
      floorListGetResponse_result_site.service,
      serializeFloorListGetResponse_result_site_service,
    );
    writer.writeAdditionalData(floorListGetResponse_result_site.additionalData);
  }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFloorListGetResponse_result_site_service(
  writer: SerializationWriter,
  floorListGetResponse_result_site_service:
    | Partial<FloorListGetResponse_result_site_service>
    | undefined
    | null = {},
): void {
  if (floorListGetResponse_result_site_service) {
    writer.writeStringValue(
      "code",
      floorListGetResponse_result_site_service.code,
    );
    writer.writeCollectionOfObjectValues<
      FloorListGetResponse_result_site_service_floor
    >(
      "floor",
      floorListGetResponse_result_site_service.floor,
      serializeFloorListGetResponse_result_site_service_floor,
    );
    writer.writeStringValue(
      "name",
      floorListGetResponse_result_site_service.name,
    );
    writer.writeAdditionalData(
      floorListGetResponse_result_site_service.additionalData,
    );
  }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFloorListGetResponse_result_site_service_floor(
  writer: SerializationWriter,
  floorListGetResponse_result_site_service_floor:
    | Partial<FloorListGetResponse_result_site_service_floor>
    | undefined
    | null = {},
): void {
  if (floorListGetResponse_result_site_service_floor) {
    writer.writeStringValue(
      "code",
      floorListGetResponse_result_site_service_floor.code,
    );
    writer.writeStringValue(
      "id",
      floorListGetResponse_result_site_service_floor.id,
    );
    writer.writeStringValue(
      "name",
      floorListGetResponse_result_site_service_floor.name,
    );
    writer.writeAdditionalData(
      floorListGetResponse_result_site_service_floor.additionalData,
    );
  }
}
/**
 * Uri template for the request builder.
 */
export const FloorListRequestBuilderUriTemplate =
  "{+baseurl}/FloorList{?callback*,output*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const FloorListRequestBuilderRequestsMetadata: RequestsMetadata = {
  get: {
    uriTemplate: FloorListRequestBuilderUriTemplate,
    responseBodyContentType: "application/json",
    adapterMethodName: "send",
    responseBodyFactory: createFloorListGetResponseFromDiscriminatorValue,
  },
};
export const GetOutputQueryParameterTypeObject = {
  Json: "json",
  Xml: "xml",
} as const;
/* tslint:enable */
/* eslint-enable */
