/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
  type AdditionalDataHolder,
  type BaseRequestBuilder,
  type DateOnly,
  type Parsable,
  type ParsableFactory,
  type ParseNode,
  type RequestConfiguration,
  type RequestInformation,
  type RequestsMetadata,
  type SerializationWriter,
} from "@microsoft/kiota-abstractions";

export interface ActressSearchGetResponse
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The request property
   */
  request?: ActressSearchGetResponse_request | null;
  /**
   * The result property
   */
  result?: ActressSearchGetResponse_result | null;
}
export interface ActressSearchGetResponse_request
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The parameters property
   */
  parameters?: ActressSearchGetResponse_request_parameters | null;
}
export interface ActressSearchGetResponse_request_parameters
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The affiliate_id property
   */
  affiliateId?: string | null;
  /**
   * The api_id property
   */
  apiId?: string | null;
  /**
   * The bust property
   */
  bust?: string | null;
  /**
   * The hits property
   */
  hits?: string | null;
  /**
   * The keyword property
   */
  keyword?: string | null;
  /**
   * The output property
   */
  output?: string | null;
  /**
   * The sort property
   */
  sort?: string | null;
  /**
   * The waist property
   */
  waist?: string | null;
}
export interface ActressSearchGetResponse_result
  extends AdditionalDataHolder, Parsable {
  /**
   * The actress property
   */
  actress?: ActressSearchGetResponse_result_actress[] | null;
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The first_position property
   */
  firstPosition?: number | null;
  /**
   * The result_count property
   */
  resultCount?: number | null;
  /**
   * The status property
   */
  status?: string | null;
  /**
   * The total_count property
   */
  totalCount?: string | null;
}
export interface ActressSearchGetResponse_result_actress
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The birthday property
   */
  birthday?: string | null;
  /**
   * The blood_type property
   */
  bloodType?: string | null;
  /**
   * The bust property
   */
  bust?: string | null;
  /**
   * The cup property
   */
  cup?: string | null;
  /**
   * The height property
   */
  height?: string | null;
  /**
   * The hip property
   */
  hip?: string | null;
  /**
   * The hobby property
   */
  hobby?: string | null;
  /**
   * The id property
   */
  id?: string | null;
  /**
   * The imageURL property
   */
  imageURL?: ActressSearchGetResponse_result_actress_imageURL | null;
  /**
   * The listURL property
   */
  listURL?: ActressSearchGetResponse_result_actress_listURL | null;
  /**
   * The name property
   */
  name?: string | null;
  /**
   * The prefectures property
   */
  prefectures?: string | null;
  /**
   * The ruby property
   */
  ruby?: string | null;
  /**
   * The waist property
   */
  waist?: string | null;
}
export interface ActressSearchGetResponse_result_actress_imageURL
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The large property
   */
  large?: string | null;
  /**
   * The small property
   */
  small?: string | null;
}
export interface ActressSearchGetResponse_result_actress_listURL
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The digital property
   */
  digital?: string | null;
  /**
   * The mono property
   */
  mono?: string | null;
  /**
   * The monthly property
   */
  monthly?: string | null;
  /**
   * The ppm property
   */
  ppm?: string | null;
  /**
   * The rental property
   */
  rental?: string | null;
}
/**
 * Builds and executes requests for operations under /ActressSearch
 */
export interface ActressSearchRequestBuilder
  extends BaseRequestBuilder<ActressSearchRequestBuilder> {
  /**
   * 女優情報を取得することが可能なAPIです。```curlhttps://api.dmm.com/affiliate/v3/ActressSearch?api_id=[APIID]&affiliate_id=[アフィリエイトID]&keyword=%e3%81%82%e3%81%95%e3%81%bf&gte_bust=90&lte_waist=60&sort=-bust&hits=10&offset=10&output=json````gte_`と`lte_`で始まるパラメータは範囲条件として使用します。gte_bust=90ならバスト90cm以上、lte_bust=90ならバスト90cm以下、gte_bust=90&lte_bust=100ならバスト90cm以上～100cm以下
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {Promise<ActressSearchGetResponse>}
   */
  get(
    requestConfiguration?:
      | RequestConfiguration<ActressSearchRequestBuilderGetQueryParameters>
      | undefined,
  ): Promise<ActressSearchGetResponse | undefined>;
  /**
   * 女優情報を取得することが可能なAPIです。```curlhttps://api.dmm.com/affiliate/v3/ActressSearch?api_id=[APIID]&affiliate_id=[アフィリエイトID]&keyword=%e3%81%82%e3%81%95%e3%81%bf&gte_bust=90&lte_waist=60&sort=-bust&hits=10&offset=10&output=json````gte_`と`lte_`で始まるパラメータは範囲条件として使用します。gte_bust=90ならバスト90cm以上、lte_bust=90ならバスト90cm以下、gte_bust=90&lte_bust=100ならバスト90cm以上～100cm以下
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {RequestInformation}
   */
  toGetRequestInformation(
    requestConfiguration?:
      | RequestConfiguration<ActressSearchRequestBuilderGetQueryParameters>
      | undefined,
  ): RequestInformation;
}
/**
 * 女優情報を取得することが可能なAPIです。```curlhttps://api.dmm.com/affiliate/v3/ActressSearch?api_id=[APIID]&affiliate_id=[アフィリエイトID]&keyword=%e3%81%82%e3%81%95%e3%81%bf&gte_bust=90&lte_waist=60&sort=-bust&hits=10&offset=10&output=json````gte_`と`lte_`で始まるパラメータは範囲条件として使用します。gte_bust=90ならバスト90cm以上、lte_bust=90ならバスト90cm以下、gte_bust=90&lte_bust=100ならバスト90cm以上～100cm以下
 */
export interface ActressSearchRequestBuilderGetQueryParameters {
  /**
   * 女優ID
   */
  actressId?: string;
  /**
   * 出力形式jsonで指定した場合に、このパラメータでコールバック関数名を指定すると、JSONP形式で出力されます
   */
  callback?: string;
  /**
   * 生年月日 (以降)
   */
  gteBirthday?: DateOnly;
  /**
   * バスト (以上)
   */
  gteBust?: number;
  /**
   * 身長 (以上)
   */
  gteHeight?: number;
  /**
   * ヒップ (以上)
   */
  gteHip?: number;
  /**
   * ウエスト (以上)
   */
  gteWaist?: number;
  /**
   * 取得件数
   */
  hits?: number;
  /**
   * 頭文字(50音) 50音をUTF-8で指定
   */
  initial?: string;
  /**
   * キーワード UTF-8で指定
   */
  keyword?: string;
  /**
   * 生年月日 (以前)
   */
  lteBirthday?: DateOnly;
  /**
   * バスト (以下)
   */
  lteBust?: number;
  /**
   * 身長 (以下)
   */
  lteHeight?: number;
  /**
   * ヒップ (以下)
   */
  lteHip?: number;
  /**
   * ウエスト (以下)
   */
  lteWaist?: number;
  /**
   * 検索開始位置
   */
  offset?: number;
  /**
   * 出力形式
   */
  output?: GetOutputQueryParameterType;
  /**
   * ソート順 名前昇順：name 名前降順：-name バスト昇順：bust バスト降順：-bust ウエスト昇順：waist ウエスト降順：-waist ヒップ昇順：hip ヒップ降順：-hip 身長昇順：height 身長降順：-height 生年月日昇順：birthday 生年月日降順：-birthday 女優ID昇順：id 女優ID降順：-id
   */
  sort?: GetSortQueryParameterType;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ActressSearchGetResponse_request_parameters}
 */
// @ts-ignore
export function createActressSearchGetResponse_request_parametersFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoActressSearchGetResponse_request_parameters;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ActressSearchGetResponse_request}
 */
// @ts-ignore
export function createActressSearchGetResponse_requestFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoActressSearchGetResponse_request;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ActressSearchGetResponse_result_actress_imageURL}
 */
// @ts-ignore
export function createActressSearchGetResponse_result_actress_imageURLFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoActressSearchGetResponse_result_actress_imageURL;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ActressSearchGetResponse_result_actress_listURL}
 */
// @ts-ignore
export function createActressSearchGetResponse_result_actress_listURLFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoActressSearchGetResponse_result_actress_listURL;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ActressSearchGetResponse_result_actress}
 */
// @ts-ignore
export function createActressSearchGetResponse_result_actressFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoActressSearchGetResponse_result_actress;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ActressSearchGetResponse_result}
 */
// @ts-ignore
export function createActressSearchGetResponse_resultFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoActressSearchGetResponse_result;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ActressSearchGetResponse}
 */
// @ts-ignore
export function createActressSearchGetResponseFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoActressSearchGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoActressSearchGetResponse(
  actressSearchGetResponse: Partial<ActressSearchGetResponse> | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "request": (n) => {
      actressSearchGetResponse.request = n.getObjectValue<
        ActressSearchGetResponse_request
      >(createActressSearchGetResponse_requestFromDiscriminatorValue);
    },
    "result": (n) => {
      actressSearchGetResponse.result = n.getObjectValue<
        ActressSearchGetResponse_result
      >(createActressSearchGetResponse_resultFromDiscriminatorValue);
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoActressSearchGetResponse_request(
  actressSearchGetResponse_request:
    | Partial<ActressSearchGetResponse_request>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "parameters": (n) => {
      actressSearchGetResponse_request.parameters = n.getObjectValue<
        ActressSearchGetResponse_request_parameters
      >(createActressSearchGetResponse_request_parametersFromDiscriminatorValue);
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoActressSearchGetResponse_request_parameters(
  actressSearchGetResponse_request_parameters:
    | Partial<ActressSearchGetResponse_request_parameters>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "affiliate_id": (n) => {
      actressSearchGetResponse_request_parameters.affiliateId = n
        .getStringValue();
    },
    "api_id": (n) => {
      actressSearchGetResponse_request_parameters.apiId = n.getStringValue();
    },
    "bust": (n) => {
      actressSearchGetResponse_request_parameters.bust = n.getStringValue();
    },
    "hits": (n) => {
      actressSearchGetResponse_request_parameters.hits = n.getStringValue();
    },
    "keyword": (n) => {
      actressSearchGetResponse_request_parameters.keyword = n.getStringValue();
    },
    "output": (n) => {
      actressSearchGetResponse_request_parameters.output = n.getStringValue();
    },
    "sort": (n) => {
      actressSearchGetResponse_request_parameters.sort = n.getStringValue();
    },
    "waist": (n) => {
      actressSearchGetResponse_request_parameters.waist = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoActressSearchGetResponse_result(
  actressSearchGetResponse_result:
    | Partial<ActressSearchGetResponse_result>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "actress": (n) => {
      actressSearchGetResponse_result.actress = n.getCollectionOfObjectValues<
        ActressSearchGetResponse_result_actress
      >(createActressSearchGetResponse_result_actressFromDiscriminatorValue);
    },
    "first_position": (n) => {
      actressSearchGetResponse_result.firstPosition = n.getNumberValue();
    },
    "result_count": (n) => {
      actressSearchGetResponse_result.resultCount = n.getNumberValue();
    },
    "status": (n) => {
      actressSearchGetResponse_result.status = n.getStringValue();
    },
    "total_count": (n) => {
      actressSearchGetResponse_result.totalCount = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoActressSearchGetResponse_result_actress(
  actressSearchGetResponse_result_actress:
    | Partial<ActressSearchGetResponse_result_actress>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "birthday": (n) => {
      actressSearchGetResponse_result_actress.birthday = n.getStringValue();
    },
    "blood_type": (n) => {
      actressSearchGetResponse_result_actress.bloodType = n.getStringValue();
    },
    "bust": (n) => {
      actressSearchGetResponse_result_actress.bust = n.getStringValue();
    },
    "cup": (n) => {
      actressSearchGetResponse_result_actress.cup = n.getStringValue();
    },
    "height": (n) => {
      actressSearchGetResponse_result_actress.height = n.getStringValue();
    },
    "hip": (n) => {
      actressSearchGetResponse_result_actress.hip = n.getStringValue();
    },
    "hobby": (n) => {
      actressSearchGetResponse_result_actress.hobby = n.getStringValue();
    },
    "id": (n) => {
      actressSearchGetResponse_result_actress.id = n.getStringValue();
    },
    "imageURL": (n) => {
      actressSearchGetResponse_result_actress.imageURL = n.getObjectValue<
        ActressSearchGetResponse_result_actress_imageURL
      >(createActressSearchGetResponse_result_actress_imageURLFromDiscriminatorValue);
    },
    "listURL": (n) => {
      actressSearchGetResponse_result_actress.listURL = n.getObjectValue<
        ActressSearchGetResponse_result_actress_listURL
      >(createActressSearchGetResponse_result_actress_listURLFromDiscriminatorValue);
    },
    "name": (n) => {
      actressSearchGetResponse_result_actress.name = n.getStringValue();
    },
    "prefectures": (n) => {
      actressSearchGetResponse_result_actress.prefectures = n.getStringValue();
    },
    "ruby": (n) => {
      actressSearchGetResponse_result_actress.ruby = n.getStringValue();
    },
    "waist": (n) => {
      actressSearchGetResponse_result_actress.waist = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoActressSearchGetResponse_result_actress_imageURL(
  actressSearchGetResponse_result_actress_imageURL:
    | Partial<ActressSearchGetResponse_result_actress_imageURL>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "large": (n) => {
      actressSearchGetResponse_result_actress_imageURL.large = n
        .getStringValue();
    },
    "small": (n) => {
      actressSearchGetResponse_result_actress_imageURL.small = n
        .getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoActressSearchGetResponse_result_actress_listURL(
  actressSearchGetResponse_result_actress_listURL:
    | Partial<ActressSearchGetResponse_result_actress_listURL>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "digital": (n) => {
      actressSearchGetResponse_result_actress_listURL.digital = n
        .getStringValue();
    },
    "mono": (n) => {
      actressSearchGetResponse_result_actress_listURL.mono = n.getStringValue();
    },
    "monthly": (n) => {
      actressSearchGetResponse_result_actress_listURL.monthly = n
        .getStringValue();
    },
    "ppm": (n) => {
      actressSearchGetResponse_result_actress_listURL.ppm = n.getStringValue();
    },
    "rental": (n) => {
      actressSearchGetResponse_result_actress_listURL.rental = n
        .getStringValue();
    },
  };
}
export type GetOutputQueryParameterType =
  (typeof GetOutputQueryParameterTypeObject)[
    keyof typeof GetOutputQueryParameterTypeObject
  ];
export type GetSortQueryParameterType =
  (typeof GetSortQueryParameterTypeObject)[
    keyof typeof GetSortQueryParameterTypeObject
  ];
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeActressSearchGetResponse(
  writer: SerializationWriter,
  actressSearchGetResponse:
    | Partial<ActressSearchGetResponse>
    | undefined
    | null = {},
): void {
  if (actressSearchGetResponse) {
    writer.writeObjectValue<ActressSearchGetResponse_request>(
      "request",
      actressSearchGetResponse.request,
      serializeActressSearchGetResponse_request,
    );
    writer.writeObjectValue<ActressSearchGetResponse_result>(
      "result",
      actressSearchGetResponse.result,
      serializeActressSearchGetResponse_result,
    );
    writer.writeAdditionalData(actressSearchGetResponse.additionalData);
  }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeActressSearchGetResponse_request(
  writer: SerializationWriter,
  actressSearchGetResponse_request:
    | Partial<ActressSearchGetResponse_request>
    | undefined
    | null = {},
): void {
  if (actressSearchGetResponse_request) {
    writer.writeObjectValue<ActressSearchGetResponse_request_parameters>(
      "parameters",
      actressSearchGetResponse_request.parameters,
      serializeActressSearchGetResponse_request_parameters,
    );
    writer.writeAdditionalData(actressSearchGetResponse_request.additionalData);
  }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeActressSearchGetResponse_request_parameters(
  writer: SerializationWriter,
  actressSearchGetResponse_request_parameters:
    | Partial<ActressSearchGetResponse_request_parameters>
    | undefined
    | null = {},
): void {
  if (actressSearchGetResponse_request_parameters) {
    writer.writeStringValue(
      "affiliate_id",
      actressSearchGetResponse_request_parameters.affiliateId,
    );
    writer.writeStringValue(
      "api_id",
      actressSearchGetResponse_request_parameters.apiId,
    );
    writer.writeStringValue(
      "bust",
      actressSearchGetResponse_request_parameters.bust,
    );
    writer.writeStringValue(
      "hits",
      actressSearchGetResponse_request_parameters.hits,
    );
    writer.writeStringValue(
      "keyword",
      actressSearchGetResponse_request_parameters.keyword,
    );
    writer.writeStringValue(
      "output",
      actressSearchGetResponse_request_parameters.output,
    );
    writer.writeStringValue(
      "sort",
      actressSearchGetResponse_request_parameters.sort,
    );
    writer.writeStringValue(
      "waist",
      actressSearchGetResponse_request_parameters.waist,
    );
    writer.writeAdditionalData(
      actressSearchGetResponse_request_parameters.additionalData,
    );
  }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeActressSearchGetResponse_result(
  writer: SerializationWriter,
  actressSearchGetResponse_result:
    | Partial<ActressSearchGetResponse_result>
    | undefined
    | null = {},
): void {
  if (actressSearchGetResponse_result) {
    writer.writeCollectionOfObjectValues<
      ActressSearchGetResponse_result_actress
    >(
      "actress",
      actressSearchGetResponse_result.actress,
      serializeActressSearchGetResponse_result_actress,
    );
    writer.writeNumberValue(
      "first_position",
      actressSearchGetResponse_result.firstPosition,
    );
    writer.writeNumberValue(
      "result_count",
      actressSearchGetResponse_result.resultCount,
    );
    writer.writeStringValue("status", actressSearchGetResponse_result.status);
    writer.writeStringValue(
      "total_count",
      actressSearchGetResponse_result.totalCount,
    );
    writer.writeAdditionalData(actressSearchGetResponse_result.additionalData);
  }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeActressSearchGetResponse_result_actress(
  writer: SerializationWriter,
  actressSearchGetResponse_result_actress:
    | Partial<ActressSearchGetResponse_result_actress>
    | undefined
    | null = {},
): void {
  if (actressSearchGetResponse_result_actress) {
    writer.writeStringValue(
      "birthday",
      actressSearchGetResponse_result_actress.birthday,
    );
    writer.writeStringValue(
      "blood_type",
      actressSearchGetResponse_result_actress.bloodType,
    );
    writer.writeStringValue(
      "bust",
      actressSearchGetResponse_result_actress.bust,
    );
    writer.writeStringValue("cup", actressSearchGetResponse_result_actress.cup);
    writer.writeStringValue(
      "height",
      actressSearchGetResponse_result_actress.height,
    );
    writer.writeStringValue("hip", actressSearchGetResponse_result_actress.hip);
    writer.writeStringValue(
      "hobby",
      actressSearchGetResponse_result_actress.hobby,
    );
    writer.writeStringValue("id", actressSearchGetResponse_result_actress.id);
    writer.writeObjectValue<ActressSearchGetResponse_result_actress_imageURL>(
      "imageURL",
      actressSearchGetResponse_result_actress.imageURL,
      serializeActressSearchGetResponse_result_actress_imageURL,
    );
    writer.writeObjectValue<ActressSearchGetResponse_result_actress_listURL>(
      "listURL",
      actressSearchGetResponse_result_actress.listURL,
      serializeActressSearchGetResponse_result_actress_listURL,
    );
    writer.writeStringValue(
      "name",
      actressSearchGetResponse_result_actress.name,
    );
    writer.writeStringValue(
      "prefectures",
      actressSearchGetResponse_result_actress.prefectures,
    );
    writer.writeStringValue(
      "ruby",
      actressSearchGetResponse_result_actress.ruby,
    );
    writer.writeStringValue(
      "waist",
      actressSearchGetResponse_result_actress.waist,
    );
    writer.writeAdditionalData(
      actressSearchGetResponse_result_actress.additionalData,
    );
  }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeActressSearchGetResponse_result_actress_imageURL(
  writer: SerializationWriter,
  actressSearchGetResponse_result_actress_imageURL:
    | Partial<ActressSearchGetResponse_result_actress_imageURL>
    | undefined
    | null = {},
): void {
  if (actressSearchGetResponse_result_actress_imageURL) {
    writer.writeStringValue(
      "large",
      actressSearchGetResponse_result_actress_imageURL.large,
    );
    writer.writeStringValue(
      "small",
      actressSearchGetResponse_result_actress_imageURL.small,
    );
    writer.writeAdditionalData(
      actressSearchGetResponse_result_actress_imageURL.additionalData,
    );
  }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeActressSearchGetResponse_result_actress_listURL(
  writer: SerializationWriter,
  actressSearchGetResponse_result_actress_listURL:
    | Partial<ActressSearchGetResponse_result_actress_listURL>
    | undefined
    | null = {},
): void {
  if (actressSearchGetResponse_result_actress_listURL) {
    writer.writeStringValue(
      "digital",
      actressSearchGetResponse_result_actress_listURL.digital,
    );
    writer.writeStringValue(
      "mono",
      actressSearchGetResponse_result_actress_listURL.mono,
    );
    writer.writeStringValue(
      "monthly",
      actressSearchGetResponse_result_actress_listURL.monthly,
    );
    writer.writeStringValue(
      "ppm",
      actressSearchGetResponse_result_actress_listURL.ppm,
    );
    writer.writeStringValue(
      "rental",
      actressSearchGetResponse_result_actress_listURL.rental,
    );
    writer.writeAdditionalData(
      actressSearchGetResponse_result_actress_listURL.additionalData,
    );
  }
}
/**
 * Uri template for the request builder.
 */
export const ActressSearchRequestBuilderUriTemplate =
  "{+baseurl}/ActressSearch{?actress_id*,callback*,gte_birthday*,gte_bust*,gte_height*,gte_hip*,gte_waist*,hits*,initial*,keyword*,lte_birthday*,lte_bust*,lte_height*,lte_hip*,lte_waist*,offset*,output*,sort*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const ActressSearchRequestBuilderGetQueryParametersMapper: Record<
  string,
  string
> = {
  "actressId": "actress_id",
  "gteBirthday": "gte_birthday",
  "gteBust": "gte_bust",
  "gteHeight": "gte_height",
  "gteHip": "gte_hip",
  "gteWaist": "gte_waist",
  "lteBirthday": "lte_birthday",
  "lteBust": "lte_bust",
  "lteHeight": "lte_height",
  "lteHip": "lte_hip",
  "lteWaist": "lte_waist",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ActressSearchRequestBuilderRequestsMetadata: RequestsMetadata = {
  get: {
    uriTemplate: ActressSearchRequestBuilderUriTemplate,
    responseBodyContentType: "application/json",
    adapterMethodName: "send",
    responseBodyFactory: createActressSearchGetResponseFromDiscriminatorValue,
    queryParametersMapper: ActressSearchRequestBuilderGetQueryParametersMapper,
  },
};
export const GetOutputQueryParameterTypeObject = {
  Json: "json",
  Xml: "xml",
} as const;
export const GetSortQueryParameterTypeObject = {
  Name: "name",
  Minus_name: "-name",
  Bust: "bust",
  Minus_bust: "-bust",
  Waist: "waist",
  Minus_waist: "-waist",
  Hip: "hip",
  Minus_hip: "-hip",
  Height: "height",
  Minus_height: "-height",
  Birthday: "birthday",
  Minus_birthday: "-birthday",
  Id: "id",
  Minus_id: "-id",
} as const;
/* tslint:enable */
/* eslint-enable */
