/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
  type AdditionalDataHolder,
  type BaseRequestBuilder,
  type Parsable,
  type ParsableFactory,
  type ParseNode,
  type RequestConfiguration,
  type RequestInformation,
  type RequestsMetadata,
  type SerializationWriter,
} from "@microsoft/kiota-abstractions";

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MakerSearchGetResponse_request_parameters}
 */
// @ts-ignore
export function createMakerSearchGetResponse_request_parametersFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoMakerSearchGetResponse_request_parameters;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MakerSearchGetResponse_request}
 */
// @ts-ignore
export function createMakerSearchGetResponse_requestFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoMakerSearchGetResponse_request;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MakerSearchGetResponse_result_maker}
 */
// @ts-ignore
export function createMakerSearchGetResponse_result_makerFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoMakerSearchGetResponse_result_maker;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MakerSearchGetResponse_result}
 */
// @ts-ignore
export function createMakerSearchGetResponse_resultFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoMakerSearchGetResponse_result;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MakerSearchGetResponse}
 */
// @ts-ignore
export function createMakerSearchGetResponseFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoMakerSearchGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMakerSearchGetResponse(
  makerSearchGetResponse: Partial<MakerSearchGetResponse> | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "request": (n) => {
      makerSearchGetResponse.request = n.getObjectValue<
        MakerSearchGetResponse_request
      >(createMakerSearchGetResponse_requestFromDiscriminatorValue);
    },
    "result": (n) => {
      makerSearchGetResponse.result = n.getObjectValue<
        MakerSearchGetResponse_result
      >(createMakerSearchGetResponse_resultFromDiscriminatorValue);
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMakerSearchGetResponse_request(
  makerSearchGetResponse_request:
    | Partial<MakerSearchGetResponse_request>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "parameters": (n) => {
      makerSearchGetResponse_request.parameters = n.getObjectValue<
        MakerSearchGetResponse_request_parameters
      >(createMakerSearchGetResponse_request_parametersFromDiscriminatorValue);
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMakerSearchGetResponse_request_parameters(
  makerSearchGetResponse_request_parameters:
    | Partial<MakerSearchGetResponse_request_parameters>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "affiliate_id": (n) => {
      makerSearchGetResponse_request_parameters.affiliateId = n
        .getStringValue();
    },
    "api_id": (n) => {
      makerSearchGetResponse_request_parameters.apiId = n.getStringValue();
    },
    "floor_id": (n) => {
      makerSearchGetResponse_request_parameters.floorId = n.getStringValue();
    },
    "hits": (n) => {
      makerSearchGetResponse_request_parameters.hits = n.getStringValue();
    },
    "offset": (n) => {
      makerSearchGetResponse_request_parameters.offset = n.getStringValue();
    },
    "output": (n) => {
      makerSearchGetResponse_request_parameters.output = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMakerSearchGetResponse_result(
  makerSearchGetResponse_result:
    | Partial<MakerSearchGetResponse_result>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "first_position": (n) => {
      makerSearchGetResponse_result.firstPosition = n.getNumberValue();
    },
    "floor_code": (n) => {
      makerSearchGetResponse_result.floorCode = n.getStringValue();
    },
    "floor_id": (n) => {
      makerSearchGetResponse_result.floorId = n.getStringValue();
    },
    "floor_name": (n) => {
      makerSearchGetResponse_result.floorName = n.getStringValue();
    },
    "maker": (n) => {
      makerSearchGetResponse_result.maker = n.getCollectionOfObjectValues<
        MakerSearchGetResponse_result_maker
      >(createMakerSearchGetResponse_result_makerFromDiscriminatorValue);
    },
    "result_count": (n) => {
      makerSearchGetResponse_result.resultCount = n.getNumberValue();
    },
    "service_code": (n) => {
      makerSearchGetResponse_result.serviceCode = n.getStringValue();
    },
    "service_name": (n) => {
      makerSearchGetResponse_result.serviceName = n.getStringValue();
    },
    "site_code": (n) => {
      makerSearchGetResponse_result.siteCode = n.getStringValue();
    },
    "site_name": (n) => {
      makerSearchGetResponse_result.siteName = n.getStringValue();
    },
    "status": (n) => {
      makerSearchGetResponse_result.status = n.getStringValue();
    },
    "total_count": (n) => {
      makerSearchGetResponse_result.totalCount = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMakerSearchGetResponse_result_maker(
  makerSearchGetResponse_result_maker:
    | Partial<MakerSearchGetResponse_result_maker>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "list_url": (n) => {
      makerSearchGetResponse_result_maker.listUrl = n.getStringValue();
    },
    "maker_id": (n) => {
      makerSearchGetResponse_result_maker.makerId = n.getStringValue();
    },
    "name": (n) => {
      makerSearchGetResponse_result_maker.name = n.getStringValue();
    },
    "ruby": (n) => {
      makerSearchGetResponse_result_maker.ruby = n.getStringValue();
    },
  };
}
export type GetOutputQueryParameterType =
  (typeof GetOutputQueryParameterTypeObject)[
    keyof typeof GetOutputQueryParameterTypeObject
  ];
/**
 * メーカー一覧
 */
export interface MakerSearchGetResponse extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The request property
   */
  request?: MakerSearchGetResponse_request | null;
  /**
   * The result property
   */
  result?: MakerSearchGetResponse_result | null;
}
export interface MakerSearchGetResponse_request
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The parameters property
   */
  parameters?: MakerSearchGetResponse_request_parameters | null;
}
export interface MakerSearchGetResponse_request_parameters
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The affiliate_id property
   */
  affiliateId?: string | null;
  /**
   * The api_id property
   */
  apiId?: string | null;
  /**
   * The floor_id property
   */
  floorId?: string | null;
  /**
   * The hits property
   */
  hits?: string | null;
  /**
   * The offset property
   */
  offset?: string | null;
  /**
   * The output property
   */
  output?: string | null;
}
export interface MakerSearchGetResponse_result
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The first_position property
   */
  firstPosition?: number | null;
  /**
   * The floor_code property
   */
  floorCode?: string | null;
  /**
   * The floor_id property
   */
  floorId?: string | null;
  /**
   * The floor_name property
   */
  floorName?: string | null;
  /**
   * The maker property
   */
  maker?: MakerSearchGetResponse_result_maker[] | null;
  /**
   * The result_count property
   */
  resultCount?: number | null;
  /**
   * The service_code property
   */
  serviceCode?: string | null;
  /**
   * The service_name property
   */
  serviceName?: string | null;
  /**
   * The site_code property
   */
  siteCode?: string | null;
  /**
   * The site_name property
   */
  siteName?: string | null;
  /**
   * The status property
   */
  status?: string | null;
  /**
   * The total_count property
   */
  totalCount?: string | null;
}
export interface MakerSearchGetResponse_result_maker
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The list_url property
   */
  listUrl?: string | null;
  /**
   * The maker_id property
   */
  makerId?: string | null;
  /**
   * The name property
   */
  name?: string | null;
  /**
   * The ruby property
   */
  ruby?: string | null;
}
/**
 * Builds and executes requests for operations under /MakerSearch
 */
export interface MakerSearchRequestBuilder
  extends BaseRequestBuilder<MakerSearchRequestBuilder> {
  /**
   * メーカー一覧を取得することが可能がAPIです。```curlhttps://api.dmm.com/affiliate/v3/MakerSearch?api_id=[APIID]&affiliate_id=[アフィリエイトID]&floor_id=43&hits=10&offset=100&output=json```
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {Promise<MakerSearchGetResponse>}
   */
  get(
    requestConfiguration?:
      | RequestConfiguration<MakerSearchRequestBuilderGetQueryParameters>
      | undefined,
  ): Promise<MakerSearchGetResponse | undefined>;
  /**
   * メーカー一覧を取得することが可能がAPIです。```curlhttps://api.dmm.com/affiliate/v3/MakerSearch?api_id=[APIID]&affiliate_id=[アフィリエイトID]&floor_id=43&hits=10&offset=100&output=json```
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {RequestInformation}
   */
  toGetRequestInformation(
    requestConfiguration?:
      | RequestConfiguration<MakerSearchRequestBuilderGetQueryParameters>
      | undefined,
  ): RequestInformation;
}
/**
 * メーカー一覧を取得することが可能がAPIです。```curlhttps://api.dmm.com/affiliate/v3/MakerSearch?api_id=[APIID]&affiliate_id=[アフィリエイトID]&floor_id=43&hits=10&offset=100&output=json```
 */
export interface MakerSearchRequestBuilderGetQueryParameters {
  /**
   * 出力形式jsonで指定した場合に、このパラメータでコールバック関数名を指定すると、JSONP形式で出力されます
   */
  callback?: string;
  /**
   * フロア検索APIから取得可能なフロアID
   */
  floorId?: string;
  /**
   * 取得件数初期値：100　最大：500
   */
  hits?: number;
  /**
   * 頭文字(50音) 50音をUTF-8で指定
   */
  initial?: string;
  /**
   * 検索開始位置初期値：1
   */
  offset?: number;
  /**
   * 出力形式
   */
  output?: GetOutputQueryParameterType;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMakerSearchGetResponse(
  writer: SerializationWriter,
  makerSearchGetResponse: Partial<MakerSearchGetResponse> | undefined | null =
    {},
): void {
  if (makerSearchGetResponse) {
    writer.writeObjectValue<MakerSearchGetResponse_request>(
      "request",
      makerSearchGetResponse.request,
      serializeMakerSearchGetResponse_request,
    );
    writer.writeObjectValue<MakerSearchGetResponse_result>(
      "result",
      makerSearchGetResponse.result,
      serializeMakerSearchGetResponse_result,
    );
    writer.writeAdditionalData(makerSearchGetResponse.additionalData);
  }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMakerSearchGetResponse_request(
  writer: SerializationWriter,
  makerSearchGetResponse_request:
    | Partial<MakerSearchGetResponse_request>
    | undefined
    | null = {},
): void {
  if (makerSearchGetResponse_request) {
    writer.writeObjectValue<MakerSearchGetResponse_request_parameters>(
      "parameters",
      makerSearchGetResponse_request.parameters,
      serializeMakerSearchGetResponse_request_parameters,
    );
    writer.writeAdditionalData(makerSearchGetResponse_request.additionalData);
  }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMakerSearchGetResponse_request_parameters(
  writer: SerializationWriter,
  makerSearchGetResponse_request_parameters:
    | Partial<MakerSearchGetResponse_request_parameters>
    | undefined
    | null = {},
): void {
  if (makerSearchGetResponse_request_parameters) {
    writer.writeStringValue(
      "affiliate_id",
      makerSearchGetResponse_request_parameters.affiliateId,
    );
    writer.writeStringValue(
      "api_id",
      makerSearchGetResponse_request_parameters.apiId,
    );
    writer.writeStringValue(
      "floor_id",
      makerSearchGetResponse_request_parameters.floorId,
    );
    writer.writeStringValue(
      "hits",
      makerSearchGetResponse_request_parameters.hits,
    );
    writer.writeStringValue(
      "offset",
      makerSearchGetResponse_request_parameters.offset,
    );
    writer.writeStringValue(
      "output",
      makerSearchGetResponse_request_parameters.output,
    );
    writer.writeAdditionalData(
      makerSearchGetResponse_request_parameters.additionalData,
    );
  }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMakerSearchGetResponse_result(
  writer: SerializationWriter,
  makerSearchGetResponse_result:
    | Partial<MakerSearchGetResponse_result>
    | undefined
    | null = {},
): void {
  if (makerSearchGetResponse_result) {
    writer.writeNumberValue(
      "first_position",
      makerSearchGetResponse_result.firstPosition,
    );
    writer.writeStringValue(
      "floor_code",
      makerSearchGetResponse_result.floorCode,
    );
    writer.writeStringValue("floor_id", makerSearchGetResponse_result.floorId);
    writer.writeStringValue(
      "floor_name",
      makerSearchGetResponse_result.floorName,
    );
    writer.writeCollectionOfObjectValues<MakerSearchGetResponse_result_maker>(
      "maker",
      makerSearchGetResponse_result.maker,
      serializeMakerSearchGetResponse_result_maker,
    );
    writer.writeNumberValue(
      "result_count",
      makerSearchGetResponse_result.resultCount,
    );
    writer.writeStringValue(
      "service_code",
      makerSearchGetResponse_result.serviceCode,
    );
    writer.writeStringValue(
      "service_name",
      makerSearchGetResponse_result.serviceName,
    );
    writer.writeStringValue(
      "site_code",
      makerSearchGetResponse_result.siteCode,
    );
    writer.writeStringValue(
      "site_name",
      makerSearchGetResponse_result.siteName,
    );
    writer.writeStringValue("status", makerSearchGetResponse_result.status);
    writer.writeStringValue(
      "total_count",
      makerSearchGetResponse_result.totalCount,
    );
    writer.writeAdditionalData(makerSearchGetResponse_result.additionalData);
  }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMakerSearchGetResponse_result_maker(
  writer: SerializationWriter,
  makerSearchGetResponse_result_maker:
    | Partial<MakerSearchGetResponse_result_maker>
    | undefined
    | null = {},
): void {
  if (makerSearchGetResponse_result_maker) {
    writer.writeStringValue(
      "list_url",
      makerSearchGetResponse_result_maker.listUrl,
    );
    writer.writeStringValue(
      "maker_id",
      makerSearchGetResponse_result_maker.makerId,
    );
    writer.writeStringValue("name", makerSearchGetResponse_result_maker.name);
    writer.writeStringValue("ruby", makerSearchGetResponse_result_maker.ruby);
    writer.writeAdditionalData(
      makerSearchGetResponse_result_maker.additionalData,
    );
  }
}
/**
 * Uri template for the request builder.
 */
export const MakerSearchRequestBuilderUriTemplate =
  "{+baseurl}/MakerSearch?floor_id={floor_id}{&callback*,hits*,initial*,offset*,output*}";
export const GetOutputQueryParameterTypeObject = {
  Json: "json",
  Xml: "xml",
} as const;
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const MakerSearchRequestBuilderGetQueryParametersMapper: Record<
  string,
  string
> = {
  "floorId": "floor_id",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const MakerSearchRequestBuilderRequestsMetadata: RequestsMetadata = {
  get: {
    uriTemplate: MakerSearchRequestBuilderUriTemplate,
    responseBodyContentType: "application/json",
    adapterMethodName: "send",
    responseBodyFactory: createMakerSearchGetResponseFromDiscriminatorValue,
    queryParametersMapper: MakerSearchRequestBuilderGetQueryParametersMapper,
  },
};
/* tslint:enable */
/* eslint-enable */
