/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import {
  type AdditionalDataHolder,
  type BaseRequestBuilder,
  type Parsable,
  type ParsableFactory,
  type ParseNode,
  type RequestConfiguration,
  type RequestInformation,
  type RequestsMetadata,
  type SerializationWriter,
} from "@microsoft/kiota-abstractions";

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MakerSearchGetResponse_request_parameters}
 */
// @ts-ignore
export function createMakerSearchGetResponse_request_parametersFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoMakerSearchGetResponse_request_parameters;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MakerSearchGetResponse_request}
 */
// @ts-ignore
export function createMakerSearchGetResponse_requestFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoMakerSearchGetResponse_request;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MakerSearchGetResponse_result_maker}
 */
// @ts-ignore
export function createMakerSearchGetResponse_result_makerFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoMakerSearchGetResponse_result_maker;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MakerSearchGetResponse_result}
 */
// @ts-ignore
export function createMakerSearchGetResponse_resultFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoMakerSearchGetResponse_result;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {MakerSearchGetResponse}
 */
// @ts-ignore
export function createMakerSearchGetResponseFromDiscriminatorValue(
  parseNode: ParseNode | undefined,
): (instance?: Parsable) => Record<string, (node: ParseNode) => void> {
  return deserializeIntoMakerSearchGetResponse;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMakerSearchGetResponse(
  makerSearchGetResponse: Partial<MakerSearchGetResponse> | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "request": (n) => {
      makerSearchGetResponse.request = n.getObjectValue<
        MakerSearchGetResponse_request
      >(createMakerSearchGetResponse_requestFromDiscriminatorValue);
    },
    "result": (n) => {
      makerSearchGetResponse.result = n.getObjectValue<
        MakerSearchGetResponse_result
      >(createMakerSearchGetResponse_resultFromDiscriminatorValue);
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMakerSearchGetResponse_request(
  makerSearchGetResponse_request:
    | Partial<MakerSearchGetResponse_request>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "parameters": (n) => {
      makerSearchGetResponse_request.parameters = n.getObjectValue<
        MakerSearchGetResponse_request_parameters
      >(createMakerSearchGetResponse_request_parametersFromDiscriminatorValue);
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMakerSearchGetResponse_request_parameters(
  makerSearchGetResponse_request_parameters:
    | Partial<MakerSearchGetResponse_request_parameters>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "affiliate_id": (n) => {
      makerSearchGetResponse_request_parameters.affiliate_id = n
        .getStringValue();
    },
    "api_id": (n) => {
      makerSearchGetResponse_request_parameters.api_id = n.getStringValue();
    },
    "floor_id": (n) => {
      makerSearchGetResponse_request_parameters.floor_id = n.getStringValue();
    },
    "hits": (n) => {
      makerSearchGetResponse_request_parameters.hits = n.getStringValue();
    },
    "offset": (n) => {
      makerSearchGetResponse_request_parameters.offset = n.getStringValue();
    },
    "output": (n) => {
      makerSearchGetResponse_request_parameters.output = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMakerSearchGetResponse_result(
  makerSearchGetResponse_result:
    | Partial<MakerSearchGetResponse_result>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "first_position": (n) => {
      makerSearchGetResponse_result.first_position = n.getNumberValue();
    },
    "floor_code": (n) => {
      makerSearchGetResponse_result.floor_code = n.getStringValue();
    },
    "floor_id": (n) => {
      makerSearchGetResponse_result.floor_id = n.getStringValue();
    },
    "floor_name": (n) => {
      makerSearchGetResponse_result.floor_name = n.getStringValue();
    },
    "maker": (n) => {
      makerSearchGetResponse_result.maker = n.getCollectionOfObjectValues<
        MakerSearchGetResponse_result_maker
      >(createMakerSearchGetResponse_result_makerFromDiscriminatorValue);
    },
    "result_count": (n) => {
      makerSearchGetResponse_result.result_count = n.getNumberValue();
    },
    "service_code": (n) => {
      makerSearchGetResponse_result.service_code = n.getStringValue();
    },
    "service_name": (n) => {
      makerSearchGetResponse_result.service_name = n.getStringValue();
    },
    "site_code": (n) => {
      makerSearchGetResponse_result.site_code = n.getStringValue();
    },
    "site_name": (n) => {
      makerSearchGetResponse_result.site_name = n.getStringValue();
    },
    "status": (n) => {
      makerSearchGetResponse_result.status = n.getStringValue();
    },
    "total_count": (n) => {
      makerSearchGetResponse_result.total_count = n.getStringValue();
    },
  };
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoMakerSearchGetResponse_result_maker(
  makerSearchGetResponse_result_maker:
    | Partial<MakerSearchGetResponse_result_maker>
    | undefined = {},
): Record<string, (node: ParseNode) => void> {
  return {
    "list_url": (n) => {
      makerSearchGetResponse_result_maker.list_url = n.getStringValue();
    },
    "maker_id": (n) => {
      makerSearchGetResponse_result_maker.maker_id = n.getStringValue();
    },
    "name": (n) => {
      makerSearchGetResponse_result_maker.name = n.getStringValue();
    },
    "ruby": (n) => {
      makerSearchGetResponse_result_maker.ruby = n.getStringValue();
    },
  };
}
export type GetOutputQueryParameterType =
  (typeof GetOutputQueryParameterTypeObject)[
    keyof typeof GetOutputQueryParameterTypeObject
  ];
/**
 * メーカー一覧
 */
export interface MakerSearchGetResponse extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The request property
   */
  request?: MakerSearchGetResponse_request;
  /**
   * The result property
   */
  result?: MakerSearchGetResponse_result;
}
export interface MakerSearchGetResponse_request
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The parameters property
   */
  parameters?: MakerSearchGetResponse_request_parameters;
}
export interface MakerSearchGetResponse_request_parameters
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The affiliate_id property
   */
  affiliate_id?: string;
  /**
   * The api_id property
   */
  api_id?: string;
  /**
   * The floor_id property
   */
  floor_id?: string;
  /**
   * The hits property
   */
  hits?: string;
  /**
   * The offset property
   */
  offset?: string;
  /**
   * The output property
   */
  output?: string;
}
export interface MakerSearchGetResponse_result
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The first_position property
   */
  first_position?: number;
  /**
   * The floor_code property
   */
  floor_code?: string;
  /**
   * The floor_id property
   */
  floor_id?: string;
  /**
   * The floor_name property
   */
  floor_name?: string;
  /**
   * The maker property
   */
  maker?: MakerSearchGetResponse_result_maker[];
  /**
   * The result_count property
   */
  result_count?: number;
  /**
   * The service_code property
   */
  service_code?: string;
  /**
   * The service_name property
   */
  service_name?: string;
  /**
   * The site_code property
   */
  site_code?: string;
  /**
   * The site_name property
   */
  site_name?: string;
  /**
   * The status property
   */
  status?: string;
  /**
   * The total_count property
   */
  total_count?: string;
}
export interface MakerSearchGetResponse_result_maker
  extends AdditionalDataHolder, Parsable {
  /**
   * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
   */
  additionalData?: Record<string, unknown>;
  /**
   * The list_url property
   */
  list_url?: string;
  /**
   * The maker_id property
   */
  maker_id?: string;
  /**
   * The name property
   */
  name?: string;
  /**
   * The ruby property
   */
  ruby?: string;
}
/**
 * Builds and executes requests for operations under /MakerSearch
 */
export interface MakerSearchRequestBuilder
  extends BaseRequestBuilder<MakerSearchRequestBuilder> {
  /**
   * メーカー一覧を取得することが可能がAPIです。```curlhttps://api.dmm.com/affiliate/v3/MakerSearch?api_id=[APIID]&affiliate_id=[アフィリエイトID]&floor_id=43&hits=10&offset=100&output=json```
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {Promise<MakerSearchGetResponse>}
   */
  get(
    requestConfiguration?:
      | RequestConfiguration<MakerSearchRequestBuilderGetQueryParameters>
      | undefined,
  ): Promise<MakerSearchGetResponse | undefined>;
  /**
   * メーカー一覧を取得することが可能がAPIです。```curlhttps://api.dmm.com/affiliate/v3/MakerSearch?api_id=[APIID]&affiliate_id=[アフィリエイトID]&floor_id=43&hits=10&offset=100&output=json```
   * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
   * @returns {RequestInformation}
   */
  toGetRequestInformation(
    requestConfiguration?:
      | RequestConfiguration<MakerSearchRequestBuilderGetQueryParameters>
      | undefined,
  ): RequestInformation;
}
/**
 * メーカー一覧を取得することが可能がAPIです。```curlhttps://api.dmm.com/affiliate/v3/MakerSearch?api_id=[APIID]&affiliate_id=[アフィリエイトID]&floor_id=43&hits=10&offset=100&output=json```
 */
export interface MakerSearchRequestBuilderGetQueryParameters {
  /**
   * 出力形式jsonで指定した場合に、このパラメータでコールバック関数名を指定すると、JSONP形式で出力されます
   */
  callback?: string;
  /**
   * フロア検索APIから取得可能なフロアID
   */
  floorId?: string;
  /**
   * 取得件数初期値：100　最大：500
   */
  hits?: number;
  /**
   * 頭文字(50音) 50音をUTF-8で指定
   */
  initial?: string;
  /**
   * 検索開始位置初期値：1
   */
  offset?: number;
  /**
   * 出力形式
   */
  output?: GetOutputQueryParameterType;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMakerSearchGetResponse(
  writer: SerializationWriter,
  makerSearchGetResponse: Partial<MakerSearchGetResponse> | undefined = {},
): void {
  writer.writeObjectValue<MakerSearchGetResponse_request>(
    "request",
    makerSearchGetResponse.request,
    serializeMakerSearchGetResponse_request,
  );
  writer.writeObjectValue<MakerSearchGetResponse_result>(
    "result",
    makerSearchGetResponse.result,
    serializeMakerSearchGetResponse_result,
  );
  writer.writeAdditionalData(makerSearchGetResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMakerSearchGetResponse_request(
  writer: SerializationWriter,
  makerSearchGetResponse_request:
    | Partial<MakerSearchGetResponse_request>
    | undefined = {},
): void {
  writer.writeObjectValue<MakerSearchGetResponse_request_parameters>(
    "parameters",
    makerSearchGetResponse_request.parameters,
    serializeMakerSearchGetResponse_request_parameters,
  );
  writer.writeAdditionalData(makerSearchGetResponse_request.additionalData);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMakerSearchGetResponse_request_parameters(
  writer: SerializationWriter,
  makerSearchGetResponse_request_parameters:
    | Partial<MakerSearchGetResponse_request_parameters>
    | undefined = {},
): void {
  writer.writeStringValue(
    "affiliate_id",
    makerSearchGetResponse_request_parameters.affiliate_id,
  );
  writer.writeStringValue(
    "api_id",
    makerSearchGetResponse_request_parameters.api_id,
  );
  writer.writeStringValue(
    "floor_id",
    makerSearchGetResponse_request_parameters.floor_id,
  );
  writer.writeStringValue(
    "hits",
    makerSearchGetResponse_request_parameters.hits,
  );
  writer.writeStringValue(
    "offset",
    makerSearchGetResponse_request_parameters.offset,
  );
  writer.writeStringValue(
    "output",
    makerSearchGetResponse_request_parameters.output,
  );
  writer.writeAdditionalData(
    makerSearchGetResponse_request_parameters.additionalData,
  );
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMakerSearchGetResponse_result(
  writer: SerializationWriter,
  makerSearchGetResponse_result:
    | Partial<MakerSearchGetResponse_result>
    | undefined = {},
): void {
  writer.writeNumberValue(
    "first_position",
    makerSearchGetResponse_result.first_position,
  );
  writer.writeStringValue(
    "floor_code",
    makerSearchGetResponse_result.floor_code,
  );
  writer.writeStringValue("floor_id", makerSearchGetResponse_result.floor_id);
  writer.writeStringValue(
    "floor_name",
    makerSearchGetResponse_result.floor_name,
  );
  writer.writeCollectionOfObjectValues<MakerSearchGetResponse_result_maker>(
    "maker",
    makerSearchGetResponse_result.maker,
    serializeMakerSearchGetResponse_result_maker,
  );
  writer.writeNumberValue(
    "result_count",
    makerSearchGetResponse_result.result_count,
  );
  writer.writeStringValue(
    "service_code",
    makerSearchGetResponse_result.service_code,
  );
  writer.writeStringValue(
    "service_name",
    makerSearchGetResponse_result.service_name,
  );
  writer.writeStringValue("site_code", makerSearchGetResponse_result.site_code);
  writer.writeStringValue("site_name", makerSearchGetResponse_result.site_name);
  writer.writeStringValue("status", makerSearchGetResponse_result.status);
  writer.writeStringValue(
    "total_count",
    makerSearchGetResponse_result.total_count,
  );
  writer.writeAdditionalData(makerSearchGetResponse_result.additionalData);
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeMakerSearchGetResponse_result_maker(
  writer: SerializationWriter,
  makerSearchGetResponse_result_maker:
    | Partial<MakerSearchGetResponse_result_maker>
    | undefined = {},
): void {
  writer.writeStringValue(
    "list_url",
    makerSearchGetResponse_result_maker.list_url,
  );
  writer.writeStringValue(
    "maker_id",
    makerSearchGetResponse_result_maker.maker_id,
  );
  writer.writeStringValue("name", makerSearchGetResponse_result_maker.name);
  writer.writeStringValue("ruby", makerSearchGetResponse_result_maker.ruby);
  writer.writeAdditionalData(
    makerSearchGetResponse_result_maker.additionalData,
  );
}
/**
 * Uri template for the request builder.
 */
export const MakerSearchRequestBuilderUriTemplate =
  "{+baseurl}/MakerSearch?floor_id={floor_id}{&callback*,hits*,initial*,offset*,output*}";
export const GetOutputQueryParameterTypeObject = {
  Json: "json",
  Xml: "xml",
} as const;
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const MakerSearchRequestBuilderGetQueryParametersMapper: Record<
  string,
  string
> = {
  "floorId": "floor_id",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const MakerSearchRequestBuilderRequestsMetadata: RequestsMetadata = {
  get: {
    uriTemplate: MakerSearchRequestBuilderUriTemplate,
    responseBodyContentType: "application/json",
    adapterMethodName: "send",
    responseBodyFactory: createMakerSearchGetResponseFromDiscriminatorValue,
    queryParametersMapper: MakerSearchRequestBuilderGetQueryParametersMapper,
  },
};
/* tslint:enable */
/* eslint-enable */
